# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly. (but github refuses)
permalink:           pretty
# relative_permalinks: true ----

# this is required for mathjax ( http://gastonsanchez.com/opinion/2014/02/16/Mathjax-with-jekyll/ )
markdown: kramdown
mathjax: true


# Setup
title:               Prussia
tagline:             'Short notes on various things'
description:         'Short notes on various things - made by <a href="https://twitter.com/testingham" target="_blank">@testingham</a>.'
url:                 http://tecunningham.github.io/
baseurl:             http://tecunningham.github.io/
paginate:            5

# About/contact
author:
  name:              Tom Cunningham
  url:               https://twitter.com/testingham
  email:             tom.cunningham@gmail.com

