project:
  type: website
  output-dir: docs

freeze: true


pagetitle: "{{< meta title >}} | Tom Cunningham"
description-meta: "..."
author-meta: "Tom Cunningham"

fontsize: 11pt

website:
  title: "Tom Cunningham"
  description: "{{< meta description-meta >}}"
  site-url: "tecunningham.github.io"
  twitter-card: true
  google-analytics: UA-12027453-1
  navbar:
    right:
      - text: "About"
        href: ./about.html
      - icon: twitter
        href: https://twitter.com/testingham
      - icon: linkedin
        href: https://www.linkedin.com/in/tom-cunningham-a9433/
#      - text: "{{< iconify academicons google-scholar >}}"
      - text: "scholar"
        href: https://scholar.google.com/citations?user=MDB_DgkAAAAJ
format:
  html:
#    theme: cosmo
    css: styles.css



