project:
  type: website
  output-dir: docs

website:
  title: "tecunningham.github.io"
  navbar:
    right:
      - about.qmd
#      - icon: github
#        href: https://github.com/
      - icon: twitter
        href: https://twitter.com/testingham
      - icon: linkedin
        href: https://www.linkedin.com/in/tom-cunningham-a9433/
format:
  html:
    theme: cosmo
    css: styles.css



