<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Tom Cunningham">
<meta name="dcterms.date" content="2026-03-21">
<meta name="description" content="Tom Cunningham blog">

<title>Recursive Self-Improvement Overview | Tom Cunningham – Tom Cunningham</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

<script type="text/javascript">

(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
ga('create', 'UA-12027453-1', 'auto');

ga('send', {
  hitType: 'pageview',
  'anonymizeIp': true,
});
</script>
<script src="../site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="../site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="../site_libs/quarto-diagram/mermaid.css" rel="stylesheet">
<script>window.MathJax = {
   loader: { load: ["https://cdn.jsdelivr.net/gh/sonoisa/XyJax-v3@3.0.1/build/xypic.js"]},
   tex: {packages: {'[+]': ['xypic','bm']},
         macros: {  bm: ["\\boldsymbol{#1}", 1],
                    ut: ["\\underbrace{#1}_{\\text{#2}}", 2],
                    utt: ["\\underbrace{#1}_{\\substack{\\text{#2}\\\\\\text{#3}}}", 3] }
   }
};
</script>
<style>
   h1 {  border-bottom: 8px solid #557;}
   h2 {  border-bottom: 1px solid #ccc;}
   .greyproof {
      background-color: #f5f5f5;
      padding: 1em;
      margin: 1em 0;
      border-radius: 4px;
   }
</style>
<meta name="quarto:status" content="draft">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
<meta name="twitter:title" content="Recursive Self-Improvement Overview | Tom Cunningham">
<meta name="twitter:description" content="Tom Cunningham blog">
<meta name="twitter:card" content="summary">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner"><div id="quarto-draft-alert" class="alert alert-warning"><i class="bi bi-pencil-square"></i>Draft</div>
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Tom Cunningham</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href=".././about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com/testingham"> <i class="bi bi-twitter" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/tom-cunningham-a9433/"> <i class="bi bi-linkedin" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://tecunningham.github.io/index.xml"> <i class="bi bi-rss-fill" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://scholar.google.com/citations?user=MDB_DgkAAAAJ"> 
<span class="menu-text">scholar</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Recursive Self-Improvement Overview</h1>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Tom Cunningham </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">March 21, 2026</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<section id="summary" class="level1">
<h1>Summary</h1>
<dl>
<dt>Capabilities are growing rapidly, but they’re hard to quantify.</dt>
<dd>
There’s no consensus for a <em>scale</em> in AI capabilities. We do see fairly steady growth across many metrics: time horizon, average benchmark scores (ECI), effective compute, and predictive loss.
</dd>
<dt>Algorithmic progress seems to be around 4X/year.</dt>
<dd>
<p>We can quantify algorithmic progress with compute efficiency, i.e.&nbsp;the reduction in cost required to reach a given capability score.</p>
<p>AI researchers have been making a very consistent series of discoveries, typically estimated at increasing compute efficiency by around 4X/year (with many qualifications, discussed below).</p>
<p>The 4X/year increase in algorithmic efficiency seems to be coming from a roughly 2X/year increase in researchers.</p>
</dd>
<dt>AI speedups will cause a loop, but unclear how strong.</dt>
<dd>
<p>Historically algorithmic progress has been a function of human R&amp;D, but we now expect the AI to itself increase the rate of algorithmic progress, through increaseing effective R&amp;D: <span class="math display">\[
\xymatrix@C=1.4em@R=1.4em{
    &amp; *++[F]{R\&amp;D_t}\ar[d]
    &amp; *++[F]{R\&amp;D_{t+1}}\ar[d]
    &amp; *++[F]{R\&amp;D_{t+2}}\ar[d]
    &amp; \\
    \ar[r]
    &amp; *++[F]{Algorithms_t}\ar[r]
    &amp; *++[F]{Algorithms_{t+1}}\ar[r]\ar[ur]|{??}
    &amp; *++[F]{Algorithms_{t+2}}\ar[r]\ar[ur] &amp;
}
\]</span></p>
<p>There is still no consensus on the key diminishing-returns parameter <span class="math inline">\(\beta\)</span>. The cleanest direct AI-domain estimates I found are Ho &amp; Whitfill’s computer-vision, RL, and NLP posteriors, which are around <span class="math inline">\(\beta \approx 1.3\)</span>-<span class="math inline">\(1.6\)</span> but very noisy. By contrast, several software-intelligence-explosion calibrations imply much lower values like <span class="math inline">\(\beta \approx 0.15\)</span>-<span class="math inline">\(0.25\)</span>, while Davidson et al.&nbsp;summarize the software evidence as roughly <span class="math inline">\(\beta_S \approx 1\)</span> <span class="citation" data-cites="ho2025explosionexperiments">Ho and Whitfill (<a href="#ref-ho2025explosionexperiments" role="doc-biblioref">2025</a>)</span>; <span class="citation" data-cites="davidson2021could">Davidson (<a href="#ref-davidson2021could" role="doc-biblioref">2021</a>)</span>; <span class="citation" data-cites="davidson2026automatingairesearch">Davidson et al. (<a href="#ref-davidson2026automatingairesearch" role="doc-biblioref">2026</a>)</span>.</p>
<p>A lot of the nearby literature is actually written in terms of returns parameters like <span class="math inline">\(r=\lambda/\beta\)</span> or <span class="math inline">\(r=\lambda \alpha / \beta\)</span> rather than <span class="math inline">\(\beta\)</span> itself. That matters because <span class="math inline">\(r\)</span> is informative about long-run dynamics, but it does not separately identify <span class="math inline">\(\beta\)</span> unless the authors also pin down <span class="math inline">\(\lambda\)</span> and sometimes <span class="math inline">\(\alpha\)</span> <span class="citation" data-cites="erdil2024estimating">Erdil, Besiroglu, and Ho (<a href="#ref-erdil2024estimating" role="doc-biblioref">2024</a>)</span>; <span class="citation" data-cites="davidson2025howquickandbigwo">Davidson and Houlden (<a href="#ref-davidson2025howquickandbigwo" role="doc-biblioref">2025</a>)</span>.</p>
</dd>
<dt>AI systems are now contributing to algorithmic progress.</dt>
<dd>
<p>Until recently most AI R&amp;D was done without help by LLMs, but we now see evidence for two channels:</p>
<ol type="1">
<li><em>Augmenting AI researchers:</em> AI researchers self-report big efficiency gains, e.g. <span class="citation" data-cites="anthropic2025claude_work">Anthropic (<a href="#ref-anthropic2025claude_work" role="doc-biblioref">2025</a>)</span> self-report approximately 50% productivity gains.</li>
<li><em>Automating AI research:</em> E.g. AlphaEvolve, TTT-Discover, autoresearch.</li>
</ol>
<p>Both of these effects are hard to measure, &amp; we have a great deal of uncertainty.</p>
</dd>
</dl>
</section>
<section id="summary-old" class="level1">
<h1>Summary (OLD)</h1>
<ol type="1">
<li><p><strong>Baseline model:</strong></p>
<ul>
<li>Frontier model capability is growing at 9X/year (measured in effective compute)</li>
<li>Frontier training compute is growing at 3X/year</li>
<li>Algorithmic efficiency is growing at 3X/year</li>
<li>R&amp;D staff is growing at 2X/year.</li>
</ul></li>
<li><p><strong>Two ways we can get RSI:</strong> (1) augmentation of AI R&amp;D; (2) automation of AI R&amp;D.</p></li>
<li><p><strong>AI augmentation of R&amp;D:</strong></p>
<ul>
<li>Suppose higher levels of model capability <span class="math inline">\(A\)</span> increases the effective R&amp;D labor, <span class="math inline">\(R\)</span>, by some amount, <span class="math inline">\(R=\bar{R}A^\theta\)</span>.</li>
<li>We want to measure how <span class="math inline">\(A\)</span> affects <span class="math inline">\(R\)</span>, e.g.&nbsp;by running an uplift study with different levels of <span class="math inline">\(A\)</span>.</li>
<li>We could then plug this into a standard R&amp;D model to estimate the net degree of acceleration, with <span class="math inline">\(\dot{A}=R^\gamma A^{1-\beta}\)</span>.</li>
<li>However it’s really hard to estimate the relationship between model capability and R&amp;D worker speedup. People are poor at introspecting uplift, and it’s difficult to run experiments.</li>
<li>Notes:
<ul>
<li>The augmentation could take place through automation of subtasks, where the subtasks are complements. E.g. if they’re perfect complements then the acceleration will be <span class="math inline">\(\frac{1}{1-f}\)</span>, where <span class="math inline">\(f\)</span> is the share of tasks you’ve automated.</li>
<li>Any <span class="math inline">\(\theta&gt;0\)</span> will make growth super-exponential, AKA hyperbolic, but the magnitude matters.</li>
<li>If <span class="math inline">\(\theta\)</span> is sufficiently high (<span class="math inline">\(\theta&gt;\gamma-\beta\)</span>) then there will be self-sustaining growth, i.e.&nbsp;growth even if R&amp;D labor was constant.</li>
<li>We ignore expenditure on inference, assume that it asymptotes relatively quickly (seems reasonable).</li>
</ul></li>
</ul></li>
<li><p><strong>AI automation of R&amp;D:</strong></p>
<ul>
<li>Maintained assumption: there’s a single type of labor, though people can vary in ability, e.g.&nbsp;one person is a 10X R&amp;D worker.</li>
<li>Suppose instead that model capability <span class="math inline">\(A\)</span> can <em>autonomously</em> do AI R&amp;D work, i.e.&nbsp;it’s a perfect substitute for all human labor.</li>
<li>Now we’ll immediately be bottlenecked on inference cost: (1) we’ll get a rapid adjustment of wages &amp; inference cost until they’re equilibrated (will drive out all but the best AI researchers); (2) the price of effective R&amp;D labor will decline at the rate of inference cost decline.</li>
</ul></li>
<li><p><strong>AI partial automation (apple picking).</strong></p>
<ul>
<li>We can instead .</li>
</ul></li>
<li><p><strong>Complications:</strong></p>
<ul>
<li><strong>Measuring capability.</strong></li>
<li><strong>Bottlenecks.</strong> Some arguments that AI R&amp;D is bottlenecked by compute, e.g.&nbsp;see <span class="citation" data-cites="whitfill2025bottlenecks">Whitfill and Wu (<a href="#ref-whitfill2025bottlenecks" role="doc-biblioref">2025</a>)</span>.</li>
<li><strong>Scale-dependent algorithmic progress.</strong> <span class="citation" data-cites="gundlach2025algorithmicprogressai">Gundlach et al. (<a href="#ref-gundlach2025algorithmicprogressai" role="doc-biblioref">2025</a>)</span> argue that algorithmic progress has contributed much less.</li>
<li><strong>Data contribution.</strong> Berren Millidge argues <a href="https://www.beren.io/2025-08-02-Most-Algorithmic-Progress-is-Data-Progress/">“Most Algorithmic Progress is Data Progress”</a></li>
</ul></li>
</ol>
<div class="columns" style="height: 100vh; gap: 2rem;">
<div class="column">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2025-09-13-recursive-self-improvement-explosion-optimization_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
</div><div class="column">
<p>I think this picture gives a reasonable summary of the orthodox picture of LLM progress:</p>
<ul>
<li>Technology is getting 3X more efficient each year (blue curves shifting left)</li>
<li>Frontier training compute is increasing at 3X/year (black points shifting right)</li>
</ul>
<p>Some notes:</p>
<ol type="1">
<li>These growth-rate numbers are very ballpark, lots of disagreement.</li>
<li>The technology curve includes anything that changes the mapping of training expenditure to intelligence: declines in GPU cost, advances in algorithms, accumulation of training data, and progress in elicitation.</li>
<li>There’s no consensus on how to measure the y-axis (“model intelligence”). For many questions it actually doesn’t matter as long as we have an ordinal measure (i.e.&nbsp;we can reliably rank model intelligence). However for RSI it matters.</li>
<li>Labs are probably spending relatively more on R&amp;D than on any single frontier training run. E.g. Epoch estimates that OpenAI spent much more on experiments and broader R&amp;D compute than on the final training runs of released models.</li>
<li><span class="citation" data-cites="gundlach2025algorithmicprogressai">Gundlach et al. (<a href="#ref-gundlach2025algorithmicprogressai" role="doc-biblioref">2025</a>)</span> argue that the true technology curves are steeper, and shifting left much more slowly. Thus algorithmic progress is relatively less important, and most progress is coming from pure scale.</li>
</ol>
</div>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 32%">
<col style="width: 22%">
<col style="width: 13%">
<col style="width: 18%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th style="text-align: center;">annual growth (log)</th>
<th style="text-align: center;">worker exp.</th>
<th style="text-align: center;">experiment exp.</th>
<th style="text-align: center;">scale-free?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>GPU design</td>
<td style="text-align: center;">0.3</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">✅</td>
</tr>
<tr class="even">
<td>Model architecture</td>
<td style="text-align: center;">0.3</td>
<td style="text-align: center;">$0.5B</td>
<td style="text-align: center;">$2B</td>
<td style="text-align: center;">❌</td>
</tr>
<tr class="odd">
<td>Pretraining optimizer</td>
<td style="text-align: center;">0.3</td>
<td style="text-align: center;">$0.5B</td>
<td style="text-align: center;">$2B</td>
<td style="text-align: center;">❌</td>
</tr>
<tr class="even">
<td>Pretraining data</td>
<td style="text-align: center;">0.3</td>
<td style="text-align: center;">$0.5B</td>
<td style="text-align: center;">$0.5B</td>
<td style="text-align: center;">❌</td>
</tr>
<tr class="odd">
<td>Posttraining algorithm (RL)</td>
<td style="text-align: center;">0.3</td>
<td style="text-align: center;">$0.5B</td>
<td style="text-align: center;">$0.5B</td>
<td style="text-align: center;">❌</td>
</tr>
<tr class="even">
<td>Posttraining data</td>
<td style="text-align: center;">0.3</td>
<td style="text-align: center;">$0.5B</td>
<td style="text-align: center;">$0.5B</td>
<td style="text-align: center;">✅</td>
</tr>
<tr class="odd">
<td>Elicitation/harness</td>
<td style="text-align: center;">0.3</td>
<td style="text-align: center;">$0.5B</td>
<td style="text-align: center;">$0.1B</td>
<td style="text-align: center;">✅</td>
</tr>
<tr class="even">
<td></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td>TOTAL</td>
<td style="text-align: center;">2.1 (8X)</td>
<td style="text-align: center;">$3B</td>
<td style="text-align: center;">$6B</td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>
<dl>
<dt>Q: what determines the share spent on salary-vs-experiments?</dt>
<dd>
<ul>
<li><em>Not just determined by the cost of experimenation.</em> Even if experiments were cheap, you might want to spend a lot on them, because you’re bottlenecked on .</li>
<li><em>Random landscape → more experiments.</em> If each alternative is a completely random draw, then there’s no returns to thinking harder.</li>
<li><em>Regular landscape → more experiments.</em> Some landscapes are known to be regular, so you can just set a well-known optimization algorithm against them, and spend all your budget on collecting more datapoints, rather than tuning the algorithm. E.g. hyperparameter tuning.</li>
<li><em>Structured landscape → more thinking.</em> If the landscape has some latent structure, that requires deep reflection, then we’d expect relatively higher payoff to thinking.</li>
</ul>
</dd>
<dt>Q: where is AI likely to help?</dt>
<dd>
<ul>
<li>At each layer we have production functions Y(W,E).</li>
</ul>
</dd>
</dl>
</section>
<section id="data-on-compute-growth" class="level1">
<h1>Data on Compute Growth</h1>
<dl>
<dt>Best estimates.</dt>
<dd>
<ol type="1">
<li>Training compute expenditure has been growing around 3X/year, but will gradually fall to 1.1X/year over 2026-2030.</li>
<li>Training compute (FLOP) has been growing around 4X/year, but will fall to around 1.5X/year.</li>
<li>Algorithmic efficiency has been growing around 3X/year, it is hard to forecast future trends.</li>
</ol>
</dd>
</dl>
<table class="caption-top table">
<colgroup>
<col style="width: 29%">
<col style="width: 29%">
<col style="width: 7%">
<col style="width: 13%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>source</th>
<th>scope</th>
<th>growth</th>
<th>years</th>
<th>quantity</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="citation" data-cites="amodei2018aiandcompute">Amodei and Hernandez (<a href="#ref-amodei2018aiandcompute" role="doc-biblioref">2018</a>)</span></td>
<td>largest AI training runs</td>
<td>10X</td>
<td>2012-2018</td>
<td>training compute (FLOP)</td>
</tr>
<tr class="even">
<td><span class="citation" data-cites="epoch2025trainingcomputefrontier">Epoch AI (<a href="#ref-epoch2025trainingcomputefrontier" role="doc-biblioref">2025a</a>)</span></td>
<td>notable models</td>
<td>4.1X</td>
<td>2010-May 2024</td>
<td>training compute (FLOP)</td>
</tr>
<tr class="odd">
<td><span class="citation" data-cites="epoch2025trainingcomputefrontier">Epoch AI (<a href="#ref-epoch2025trainingcomputefrontier" role="doc-biblioref">2025a</a>)</span></td>
<td>frontier models</td>
<td>5.3X</td>
<td>2010-May 2024</td>
<td>training compute (FLOP)</td>
</tr>
<tr class="even">
<td><span class="citation" data-cites="epoch2025trainingcomputefrontier">Epoch AI (<a href="#ref-epoch2025trainingcomputefrontier" role="doc-biblioref">2025a</a>)</span></td>
<td>recent frontier models</td>
<td>4.2X</td>
<td>~2018-May 2024</td>
<td>training compute (FLOP)</td>
</tr>
<tr class="odd">
<td><span class="citation" data-cites="epoch2025trainingcomputefrontier">Epoch AI (<a href="#ref-epoch2025trainingcomputefrontier" role="doc-biblioref">2025a</a>)</span></td>
<td>frontier language models</td>
<td>5.0X</td>
<td>mid-2020-May 2024</td>
<td>training compute (FLOP)</td>
</tr>
<tr class="even">
<td><span class="citation" data-cites="epoch2025trainingcomputefrontier">Epoch AI (<a href="#ref-epoch2025trainingcomputefrontier" role="doc-biblioref">2025a</a>)</span></td>
<td>notable language models</td>
<td>9.5X</td>
<td>Jun 2017-May 2024</td>
<td>training compute (FLOP)</td>
</tr>
<tr class="odd">
<td><span class="citation" data-cites="epoch2026computetrendpost2010">Epoch AI (<a href="#ref-epoch2026computetrendpost2010" role="doc-biblioref">2026a</a>)</span></td>
<td>notable models</td>
<td>4.4-4.7X</td>
<td>2010-2026</td>
<td>training compute (FLOP)</td>
</tr>
<tr class="even">
<td><span class="citation" data-cites="EpochAIModels2025">Epoch AI (<a href="#ref-EpochAIModels2025" role="doc-biblioref">2025b</a>)</span></td>
<td>notable models graph</td>
<td>~4.6X</td>
<td>2020-Jul 2025</td>
<td>training compute (FLOP)</td>
</tr>
<tr class="odd">
<td><span class="citation" data-cites="EpochAITrends2026">Epoch AI (<a href="#ref-EpochAITrends2026" role="doc-biblioref">2026b</a>)</span></td>
<td>frontier language models</td>
<td>5X</td>
<td>2020-</td>
<td>training compute (FLOP)</td>
</tr>
<tr class="even">
<td><span class="citation" data-cites="EpochAITrends2026">Epoch AI (<a href="#ref-EpochAITrends2026" role="doc-biblioref">2026b</a>)</span></td>
<td>installed NVIDIA compute stock</td>
<td>2.3X</td>
<td>2019-</td>
<td>compute stock (FLOP/s)</td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td><span class="citation" data-cites="efrati2025openaicomputingcostproblem">Efrati and Muppidi (<a href="#ref-efrati2025openaicomputingcostproblem" role="doc-biblioref">2025</a>)</span></td>
<td>OpenAI training compute spend</td>
<td>2.3X-&gt;1.1X</td>
<td>2025-2030</td>
<td>training compute ($)</td>
</tr>
<tr class="odd">
<td><span class="citation" data-cites="EpochAITrends2026">Epoch AI (<a href="#ref-EpochAITrends2026" role="doc-biblioref">2026b</a>)</span></td>
<td>frontier language model training cost</td>
<td>3.5X</td>
<td>2020-</td>
<td>training compute ($)</td>
</tr>
<tr class="even">
<td><span class="citation" data-cites="epoch2025computescaling">Edelman and Ho (<a href="#ref-epoch2025computescaling" role="doc-biblioref">2025</a>)</span></td>
<td>OpenAI compute spend / compute stock</td>
<td>2.2X</td>
<td>2024-2025</td>
<td>compute spend / stock ($)</td>
</tr>
<tr class="odd">
<td><span class="citation" data-cites="efrati2025openaicomputingcostproblem">Efrati and Muppidi (<a href="#ref-efrati2025openaicomputingcostproblem" role="doc-biblioref">2025</a>)</span></td>
<td>OpenAI compute spend</td>
<td>2.3X-&gt;1.1X</td>
<td>2025-2030</td>
<td>total compute (training+inference) ($)</td>
</tr>
</tbody>
</table>
<dl>
<dt><span class="citation" data-cites="amodei2018aiandcompute">Amodei and Hernandez (<a href="#ref-amodei2018aiandcompute" role="doc-biblioref">2018</a>)</span> “AI and compute”</dt>
<dd>
<blockquote class="blockquote">
<p>“since 2012, the amount of compute used in the largest AI training runs has been increasing exponentially with a 3.4-month doubling time”</p>
</blockquote>
<blockquote class="blockquote">
<p>“The trend represents an increase by roughly a factor of 10 each year.”</p>
</blockquote>
</dd>
<dt><span class="citation" data-cites="EpochAITrends2026">Epoch AI (<a href="#ref-EpochAITrends2026" role="doc-biblioref">2026b</a>)</span> “Trends in Artificial Intelligence”</dt>
<dd>
<p>As of March 2026, but they say “These trends appear set to continue through 2030.”</p>
<ul>
<li>Compute stock growth: 2.3X/year (2.2X-2.5X), “the total computing power of the stock of NVIDIA chips”</li>
<li>Training compute: 5X/year (4X-6X)</li>
<li>FLOP/s per dollar: 1.37X/year (1.30X-1.45X)</li>
<li>Algorithmic progress: 3X/year (2.8X-4.4X) (“pre-training compute efficiency”)</li>
<li>Training cost: 3.5X/year (2.8X-4.4X)</li>
<li>LLM inference prices: 40X/year (10X-900X) “the cost to inference an LLM at a fixed level of performance has fallen rapidly, but unevenly across tasks”</li>
</ul>
</dd>
<dt><span class="citation" data-cites="epoch2025computescaling">Edelman and Ho (<a href="#ref-epoch2025computescaling" role="doc-biblioref">2025</a>)</span> “Compute scaling will slow down due to increasing lead times”</dt>
<dd>
<blockquote class="blockquote">
<p>“OpenAI currently likely has over $15 billion worth of compute, and this compute stock has been growing by around 2.2× each year. At that pace, current trends would predict a trillion dollar cluster around 2030 — but longer lead times would delay this to around 2035.”</p>
</blockquote>
<blockquote class="blockquote">
<p>“OpenAI’s compute spend in mid-2024 was around $6 billion, compared to roughly $13 billion mid-2025. This leads to a factor increase of around 2.2×</p>
</blockquote>
</dd>
<dt><span class="citation" data-cites="efrati2025openaicomputingcostproblem">Efrati and Muppidi (<a href="#ref-efrati2025openaicomputingcostproblem" role="doc-biblioref">2025</a>)</span> “OpenAI’s $350 Billion Computing Cost Problem”</dt>
<dd>
<p>They have leaked data on OpenAI compute expenditure forecasts, as of late 2025:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Year</th>
<th>R&amp;D Compute</th>
<th>Inference Compute</th>
<th>R&amp;D%</th>
<th>Revenue</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2025</td>
<td>~$8B</td>
<td>~$6B</td>
<td>57%</td>
<td>~$12B</td>
</tr>
<tr class="even">
<td>2026</td>
<td>~$18B (+125%)</td>
<td>~$14B (+133%)</td>
<td>56%</td>
<td>~$30B (+150%)</td>
</tr>
<tr class="odd">
<td>2027</td>
<td>~$32B (+78%)</td>
<td>~$20B (+43%)</td>
<td>62%</td>
<td>~$60B (+100%)</td>
</tr>
<tr class="even">
<td>2028</td>
<td>~$40B (+25%)</td>
<td>~$28B (+40%)</td>
<td>59%</td>
<td>~$100B (+67%)</td>
</tr>
<tr class="odd">
<td>2029</td>
<td>~$45B (+13%)</td>
<td>~$35B (+25%)</td>
<td>56%</td>
<td>~$145B (+45%)</td>
</tr>
<tr class="even">
<td>2030</td>
<td>~$50B (+11%)</td>
<td>~$50B (+43%)</td>
<td>50%</td>
<td>~$200B (+38%)</td>
</tr>
</tbody>
</table>
</dd>
<dt><span class="citation" data-cites="epoch2025trainingcomputefrontier">Epoch AI (<a href="#ref-epoch2025trainingcomputefrontier" role="doc-biblioref">2025a</a>)</span> “Training compute of frontier AI models grows by 4-5x per year”</dt>
<dd>
<blockquote class="blockquote">
<p>“compute growth in recent years is currently best described as increasing by a factor of 4-5x/year.”</p>
</blockquote>
<p>More granular estimates from the same post:</p>
<ul>
<li>notable models: 4.1x/year (90% CI: 3.7x to 4.6x) between 2010 and May 2024</li>
<li>frontier models: 5.3x/year (90% CI: 4.9x to 5.7x) between 2010 and May 2024</li>
<li>recent frontier models: 4.2x/year (90% CI: 3.6x to 4.9x) after ~2018</li>
<li>frontier language models: 5.0x/year (90% CI: 3.1x to 7.3x) after mid-2020</li>
<li>notable language models overall: 9.5x/year (90% CI: 7.4x to 12.2x) between June 2017 and May 2024</li>
</ul>
<blockquote class="blockquote">
<p>“recent frontier growth since 2018 is better described as a 4x/year trend.”</p>
</blockquote>
<blockquote class="blockquote">
<p>“notable language models overall … have grown as fast as 9x/year between June 2017 and May 2024.”</p>
</blockquote>
</dd>
<dt><span class="citation" data-cites="epoch2026computetrendpost2010">Epoch AI (<a href="#ref-epoch2026computetrendpost2010" role="doc-biblioref">2026a</a>)</span> “The training compute of notable AI models has been doubling roughly every six months”</dt>
<dd>
<blockquote class="blockquote">
<p>“Since 2010, the training compute used to create AI models has been growing at a rate of 4.4x per year.”</p>
</blockquote>
<p>Historical: 2010 onward. The same page’s regression table gives <code>4.7x / year (4.3x to 5.2x)</code>, so the safest summary is probably “roughly 4.5x/year.”</p>
</dd>
<dt><span class="citation" data-cites="whitfill2025forecastingaitimehorizon">Whitfill, Snodin, and Becker (<a href="#ref-whitfill2025forecastingaitimehorizon" role="doc-biblioref">2025</a>)</span> “Forecasting AI Time Horizon Under Compute Slowdowns”</dt>
<dd>
<p>They use OpenAI’s own compute-spend forecasts up to 2030, as reported in journalism.</p>
<p>The annualized growth rates I wrote above (<code>~2.5X/year</code> for 2026-2028, <code>~1.5X/year</code> for 2028-2030) are only rough chart reads from the figure, not direct textual claims in the paper.</p>
</dd>
<dt><span class="citation" data-cites="EpochAIModels2025">Epoch AI (<a href="#ref-EpochAIModels2025" role="doc-biblioref">2025b</a>)</span> “Data on AI Models”</dt>
<dd>
<blockquote class="blockquote">
<p>“Our comprehensive database of over 3200 models tracks key factors driving machine learning progress.”</p>
</blockquote>
<p>The interactive graph currently shows about 4.6x/year growth in FLOPs of notable models, over 2020 - July 2025 (the latest datapoint).</p>
</dd>
<dt><span class="citation" data-cites="you2025openaicomputespend">You (<a href="#ref-you2025openaicomputespend" role="doc-biblioref">2025</a>)</span> “Most of OpenAI’s 2024 compute went to experiments”</dt>
<dd>
<ul>
<li>$5B total research compute</li>
<li>$2B inference compute</li>
<li>only a minority of R&amp;D compute appears to have gone to the final training runs of released models</li>
<li>GPT-4.5 final training run was only a modest share of the total R&amp;D bucket</li>
</ul>
</dd>
</dl>
</section>
<section id="data-on-algorithmic-progress" class="level1">
<h1>Data on Algorithmic Progress</h1>
<dl>
<dt>Best estimates.</dt>
<dd>
<ul>
<li>Around 4X/year, including the entire stack (GPU, pretraining, posttraining, elicitation).</li>
</ul>
</dd>
</dl>
<table class="caption-top table">
<colgroup>
<col style="width: 21%">
<col style="width: 31%">
<col style="width: 6%">
<col style="width: 7%">
<col style="width: 31%">
</colgroup>
<thead>
<tr class="header">
<th>source</th>
<th>scope</th>
<th>progress</th>
<th>years</th>
<th>quantity</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="citation" data-cites="EpochAITrends2026">Epoch AI (<a href="#ref-EpochAITrends2026" role="doc-biblioref">2026b</a>)</span></td>
<td>AI hardware price-performance</td>
<td>1.37X</td>
<td>2012-2025</td>
<td>FLOP/s per dollar</td>
</tr>
<tr class="even">
<td><span class="citation" data-cites="ho2024algorithmicprogresslm">Ho et al. (<a href="#ref-ho2024algorithmicprogresslm" role="doc-biblioref">2024</a>)</span></td>
<td>pre-training compute efficiency</td>
<td>3X</td>
<td>2012-2023</td>
<td>compute to reach a fixed performance threshold</td>
</tr>
<tr class="odd">
<td><span class="citation" data-cites="whitfill2025forecastingaitimehorizon">Whitfill, Snodin, and Becker (<a href="#ref-whitfill2025forecastingaitimehorizon" role="doc-biblioref">2025</a>)</span></td>
<td>broad software progress implied by the time-horizon model</td>
<td>3.5X</td>
<td>2019-2025</td>
<td>effective software progress</td>
</tr>
<tr class="even">
<td><span class="citation" data-cites="ho2026leastunderstooddriver">Ho (<a href="#ref-ho2026leastunderstooddriver" role="doc-biblioref">2026</a>)</span></td>
<td>broad all-in software progress</td>
<td>10X (2X-50X)</td>
<td>recent LLM era</td>
<td>inclusive of training + post-training</td>
</tr>
<tr class="odd">
<td><span class="citation" data-cites="byrnes2026naturellmalgorithmicprogress">Byrnes (<a href="#ref-byrnes2026naturellmalgorithmicprogress" role="doc-biblioref">2026</a>)</span></td>
<td>narrow core learning algorithm improvements</td>
<td>1.3X</td>
<td>2018-2026</td>
<td>excludes data/setup-specific gains</td>
</tr>
<tr class="even">
<td><span class="citation" data-cites="gundlach2025algorithmicprogressai">Gundlach et al. (<a href="#ref-gundlach2025algorithmicprogressai" role="doc-biblioref">2025</a>)</span></td>
<td>small-scale algorithmic progress</td>
<td>1.5X</td>
<td>2012-2023</td>
<td>FLOPs required to achieve benchmark scores at small scale</td>
</tr>
<tr class="odd">
<td><span class="citation" data-cites="gundlach2025algorithmicprogressai">Gundlach et al. (<a href="#ref-gundlach2025algorithmicprogressai" role="doc-biblioref">2025</a>)</span></td>
<td>frontier-scale algorithmic progress</td>
<td>2.5X</td>
<td>2012-2023</td>
<td>FLOPs required to achieve benchmark scores at large scale</td>
</tr>
<tr class="even">
<td><span class="citation" data-cites="EpochAITrends2026">Epoch AI (<a href="#ref-EpochAITrends2026" role="doc-biblioref">2026b</a>)</span></td>
<td>pre-training compute efficiency</td>
<td>3X</td>
<td>2026-</td>
<td>forward-looking pre-training compute efficiency</td>
</tr>
<tr class="odd">
<td><span class="citation" data-cites="whitfill2026gpt2tweet">Whitfill (<a href="#ref-whitfill2026gpt2tweet" role="doc-biblioref">2026</a>)</span></td>
<td>GPT-2 replication case study: fewer FLOPs</td>
<td>1.72X</td>
<td>2019-2026</td>
<td>FLOP efficiency in training GPT-2</td>
</tr>
<tr class="even">
<td><span class="citation" data-cites="whitfill2026gpt2tweet">Whitfill (<a href="#ref-whitfill2026gpt2tweet" role="doc-biblioref">2026</a>)</span></td>
<td>GPT-2 replication case study: fewer GPUs</td>
<td>2.5X</td>
<td>2019-2026</td>
<td>GPU required to train GPT-2</td>
</tr>
</tbody>
</table>
<dl>
<dt><span class="citation" data-cites="ho2024algorithmicprogresslm">Ho et al. (<a href="#ref-ho2024algorithmicprogresslm" role="doc-biblioref">2024</a>)</span> “Algorithmic progress in language models”: 3X/year</dt>
<dd>
<blockquote class="blockquote">
<p>“the compute required to reach a set performance threshold has halved approximately every 8 months, with a 95% confidence interval of around 5 to 14 months”, i.e.&nbsp;about 2.8X/year.</p>
</blockquote>
</dd>
<dt><span class="citation" data-cites="ho2026leastunderstooddriver">Ho (<a href="#ref-ho2026leastunderstooddriver" role="doc-biblioref">2026</a>)</span> “The least understood driver of AI progress”: 10X/year.</dt>
<dd>
<blockquote class="blockquote">
<p>“So here’s my best guess: after accounting for all training compute (including post-training), I think we’re seeing software progress at around 10x per year, and my 80% credible interval would probably range from 2x to 50x per year.”</p>
</blockquote>
</dd>
<dt><span class="citation" data-cites="byrnes2026naturellmalgorithmicprogress">Byrnes (<a href="#ref-byrnes2026naturellmalgorithmicprogress" role="doc-biblioref">2026</a>)</span> “The nature of LLM algorithmic progress (v2)”: 1.3X/year.</dt>
<dd>
<blockquote class="blockquote">
<p>“apart from [transformers] the field has produced probably &lt;10x of training efficiency improvements in this category in the entire period from 2018 to today (approx. 30%/year).”</p>
</blockquote>
<p>He says he is deliberately restricting attention to core “learning algorithm” improvements, excluding data-related improvements and setup-specific optimizations.</p>
</dd>
<dt><span class="citation" data-cites="whitfill2026gpt2tweet">Whitfill (<a href="#ref-whitfill2026gpt2tweet" role="doc-biblioref">2026</a>)</span> “Post on GPT-2 to nanoGPT efficiency gains”: 2.5X/year</dt>
<dd>
<p>He estimates GPT-2 efficiency improvement was 700X over 2019-2026. Important to note that this is all at relatively small scale, so I think it is best treated as a case study rather than an estimate for frontier models.</p>
<ul>
<li>Current nanogpt SOTA is 707x faster (2.5X/year)</li>
<li>15x faster FLOP per second (on fixed hardware) (1.5X/year)</li>
<li>46x less FLOPs to reach the same val loss (1.7X/year)</li>
</ul>
<p>Also notable from nanoGPT (<span class="citation" data-cites="kellerjordan2026moddednanogpt">Jordan and contributors (<a href="#ref-kellerjordan2026moddednanogpt" role="doc-biblioref">2026</a>)</span>):</p>
<ul>
<li>Wall clock time: 30X lower (May 2024 was 45 minutes; Feb 2026 was 1.5 minutes; 5 doublings over 21 months so doubling every 4 months).</li>
<li>Cost: 2500X lower (Karpathy says his 2024 nanoGPT costs ~$20 to train the model to get GPT-2 <span class="citation" data-cites="karpathy2024llmcdiscussion">Karpathy (<a href="#ref-karpathy2024llmcdiscussion" role="doc-biblioref">2024</a>)</span>, a 2019 blog post estimated GPT-2 training cost was $50K).</li>
</ul>
</dd>
<dt><span class="citation" data-cites="gundlach2025algorithmicprogressai">Gundlach et al. (<a href="#ref-gundlach2025algorithmicprogressai" role="doc-biblioref">2025</a>)</span> “On the Origins of Algorithmic Progress in AI”: 1.5X/year.</dt>
<dd>
<blockquote class="blockquote">
<p>“Our results indicate that algorithmic progress for small models has been far slower than previously assumed, and that measures of algorithmic efficiency are strongly reference-dependent.”</p>
</blockquote>
<blockquote class="blockquote">
<p>“We find two strongly scale-dependent algorithmic innovations: LSTMs to Transformers, and Kaplan to Chinchilla re-balancing. Together, these account for 91% of total efficiency gains when extrapolating to the 2025 compute frontier.”</p>
</blockquote>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/2026-02-25-05-18-41.png" class="img-fluid figure-img"></p>
<figcaption>Figure</figcaption>
</figure>
</div>
<p>Estimates over 2012-2023:</p>
<ul>
<li>21,000X total (2.5X/year)</li>
<li>100X at small scale (1.5X/year), i.e.&nbsp;if we hadn’t scaled compute we’d only be increasing at 1.5X/year.</li>
</ul>
</dd>
<dt><span class="citation" data-cites="thompson2022importancecomputingpower">Thompson, Ge, and Manso (<a href="#ref-thompson2022importancecomputingpower" role="doc-biblioref">2022</a>)</span> “The Importance of (Exponentially More) Computing Power”</dt>
<dd>
<blockquote class="blockquote">
<p>“we assemble direct quantitative evidence of the impact that computing power has had on five domains: two computing bellwethers (Chess and Go), and three economically important applications (weather prediction, protein folding, and oil exploration). Computing power explains 49%-94% of the performance improvements in these domains.”</p>
</blockquote>
<p>[Not a direct estimate for LLM training efficiency, but useful outside-view background for the broader compute-versus-algorithms debate.]</p>
<p><img src="images/2023-11-03-17-44-38.png" class="img-fluid"></p>
</dd>
</dl>
</section>
<section id="literature-review-on-rsi-models" class="level1">
<h1>Literature Review on RSI Models</h1>
<p>We want to answer these questions:</p>
<ol type="1">
<li>Based on history of AI R&amp;D, what’s a reasonable estimate of how AI R&amp;D will change the future trajectory?</li>
<li>What is the best capability metric for estimating AI R&amp;D contribution?</li>
</ol>
<p>Basic argument:</p>
<ol type="1">
<li>Say algorithmic efficiency has been growing at 5X/year, so we can get the same intelligence for 5X lower cost.</li>
<li>We are starting to see glimmers of AI contributing to R&amp;D, &amp; want to predict how this will change the system.</li>
<li>Some alternatives in how to model this:
<ul>
<li><p><strong>Accelerant.</strong> Suppose a certain level of AI can speed up a human researcher by a certain proportion, <span class="math inline">\(\lambda\)</span>. This feedback loop should accelerate AI development, but it’s sensitive to how strong this connection is.</p></li>
<li><p><strong>Perfect substitutes.</strong> Suppose AI can do entirely autonomous research, i.e.&nbsp;it’s a perfect substitute for a human. Then we are only constrained on the cost of AI compute. Unless the cost is very high, this implies a massive acceleration in AI progress, constrained only by (a) experiment bottlenecks; (b) a ceiling to AI progress.</p></li>
<li><p><strong>Imperfect substitutes.</strong></p></li>
</ul></li>
<li>Endogenous growth setup: (1) diminishing returns to R&amp;D about 1/2; (2) increasing returns to knowledge about 1/2; these balance and get balanced growth.</li>
<li>Now we add link back from algorithms to R&amp;D, but very little guidance on how to calibrate it.</li>
</ol>
<p>Capability metrics:</p>
<ol type="1">
<li>Human researcher uplift.</li>
<li>Ability to push forward the frontier.</li>
</ol>
<p>Wrinkles:</p>
<ol type="1">
<li>Estimating algorithmic progress.</li>
<li>Scale-dependent algorithmic progress.</li>
<li>Bottlenecks on experiment compute.</li>
<li>Shape of the landscape.</li>
<li>Adding capital.</li>
</ol>
<p>Ajeya’s questions:</p>
<ol type="1">
<li>When will we have automated AI R&amp;D?
<ul>
<li>Answer: we already have automated R&amp;D.</li>
</ul></li>
<li>When we have automated AI R&amp;D, will this trigger super-exponential growth?</li>
</ol>
<p>Core model:</p>
<p><span class="math display">\[\begin{aligned}
    \utt{\dot{A}}{algorithmic}{progress}
        &amp;=\utt{R^{\gamma}}{new}{research}
            {\utt{A^{1-\beta}}{algorithms}{}}
        &amp;&amp; \text{(progress)}\\
    R&amp;=A^{\kappa}
        &amp;&amp; \text{}\\
    \dot{A}&amp;=A^{1-\beta+\kappa}\\
\end{aligned}
\]</span></p>
<table class="caption-top table">
<colgroup>
<col style="width: 30%">
<col style="width: 49%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Model</th>
<th>Summary</th>
<th><span class="math inline">\(r\)</span> used / reported</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="citation" data-cites="jones1995rd">Charles I. Jones (<a href="#ref-jones1995rd" role="doc-biblioref">1995</a>)</span> “R&amp;D-Based Models of Economic Growth.”</td>
<td>Standard endogenous growth model: (1) diminishing returns to R&amp;D; (2) positive spillovers from knowledge.</td>
<td>Defines the <span class="math inline">\(r=\lambda/\beta\)</span> object, but no numeric calibration here.</td>
</tr>
<tr class="even">
<td><span class="citation" data-cites="aghion2019artificial">Aghion, Jones, and Jones (<a href="#ref-aghion2019artificial" role="doc-biblioref">2019</a>)</span> “Artificial Intelligence and Economic Growth”</td>
<td>They first model automation of goods tasks, then extend the same task-based setup to research tasks; in the strong-form limit, AI replaces people in idea production.</td>
<td>No standalone <span class="math inline">\(r\)</span> calibration; emphasis is on task shares and <span class="math inline">\(\phi\)</span>.</td>
</tr>
<tr class="odd">
<td><span class="citation" data-cites="davidson2021could">Davidson (<a href="#ref-davidson2021could" role="doc-biblioref">2021</a>)</span> “Could Advanced AI Drive Explosive Economic Growth”</td>
<td>The simplest model is where an AI robot perfectly substitutes for a worker, &amp; then model the quantity increase of AI workers.</td>
<td>No single <span class="math inline">\(r\)</span>; imports low-<span class="math inline">\(\beta\)</span> software/hardware benchmarks via <span class="math inline">\(\phi\)</span>.</td>
</tr>
<tr class="even">
<td><span class="citation" data-cites="erdil2025gate">Erdil et al. (<a href="#ref-erdil2025gate" role="doc-biblioref">2025</a>)</span> “GATE: An Integrated Assessment Model for AI Automation”</td>
<td>They model both which tasks AI can do, and the quantity of digital workers.</td>
<td>No single Jones-style <span class="math inline">\(r\)</span> in this summary.</td>
</tr>
<tr class="odd">
<td><span class="citation" data-cites="davidson2026automatingairesearch">Davidson et al. (<a href="#ref-davidson2026automatingairesearch" role="doc-biblioref">2026</a>)</span> “When Does Automating AI Research Produce Explosive Growth?”</td>
<td>Partial automation of research tasks in a networked multi-sector R&amp;D system; goods-task automation is also present in the calibrated economy. They include cross-sector spillovers.</td>
<td>Software <span class="math inline">\(r_S \sim 1\)</span>, hardware <span class="math inline">\(r_H=5\)</span>, aggregate innovation <span class="math inline">\(r_A=0.32\)</span>.</td>
</tr>
<tr class="even">
<td><span class="citation" data-cites="jones2025aird">B. F. Jones (<a href="#ref-jones2025aird" role="doc-biblioref">2025</a>)</span> “Artificial Intelligence in Research and Development”</td>
<td>AI progress causes both (1) a larger share of tasks to be automated; (2) cost to drop for already-automated tasks. Task bottlenecks determine the net impact.</td>
<td>No single numeric <span class="math inline">\(r\)</span> in this summary.</td>
</tr>
<tr class="odd">
<td><span class="citation" data-cites="kokotajlo2025aifuturesmodel">Kokotajlo et al. (<a href="#ref-kokotajlo2025aifuturesmodel" role="doc-biblioref">2025</a>)</span> “AI Futures Model: Dec 2025 Update”</td>
<td>Stagewise automation of AI R&amp;D: coding first, then research taste / direction-setting; eventual full automation at SAR.</td>
<td>No explicit Jones-style <span class="math inline">\(r\)</span> calibration.</td>
</tr>
<tr class="even">
<td><span class="citation" data-cites="eth2025willairdautomati">Eth and Davidson (<a href="#ref-eth2025willairdautomati" role="doc-biblioref">2025</a>)</span></td>
<td>Focuses directly on whether current software R&amp;D has <span class="math inline">\(r&gt;1\)</span>, rather than estimating <span class="math inline">\(\beta\)</span> separately.</td>
<td>Argues current software research may have <span class="math inline">\(r&gt;1\)</span>.</td>
</tr>
<tr class="odd">
<td><span class="citation" data-cites="kwa2026simpleraitimelines">Kwa (<a href="#ref-kwa2026simpleraitimelines" role="doc-biblioref">2026</a>)</span> “Research Note: A Simpler AI Timelines Model Predicts 99% AI r&amp;d Automation in ~2032”</td>
<td>A simplification of <span class="citation" data-cites="kokotajlo2025aifuturesmodel">Kokotajlo et al. (<a href="#ref-kokotajlo2025aifuturesmodel" role="doc-biblioref">2025</a>)</span>, AI automates a fraction of tasks asymptotically approaching 1, assume no substitutability between tasks.</td>
<td>No explicit <span class="math inline">\(r\)</span>; assumes <span class="math inline">\(\beta \in [0.3,1]\)</span>.</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<table class="caption-top table">
<colgroup>
<col style="width: 9%">
<col style="width: 43%">
<col style="width: 47%">
</colgroup>
<thead>
<tr class="header">
<th>Mechanism</th>
<th>Examples</th>
<th>Comment</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>AI replaces R&amp;D workers</strong></td>
<td>Davidson (2021); late-stage AI Futures; strong-form Aghion et al.</td>
<td>AI is effectively a researcher/worker replacement, not just a helper on some tasks.</td>
</tr>
<tr class="even">
<td><strong>AI automates a subset of general tasks</strong></td>
<td>Aghion et al.&nbsp;(goods side); GATE; parts of Davidson et al.</td>
<td>This is the macro/task-automation framing: AI gradually expands over the economy-wide task space.</td>
</tr>
<tr class="odd">
<td><strong>AI automates a subset of R&amp;D tasks</strong></td>
<td>Aghion et al.&nbsp;(ideas side); Davidson et al.; Ben Jones; AI Futures; Kwa</td>
<td>This is the most common recent takeoff / AI-growth mechanism.</td>
</tr>
<tr class="even">
<td><strong>AI increases productivity of R&amp;D workers</strong></td>
<td>Ben Jones (fixed-task productivity gains); Besiroglu, Emery-Xu &amp; Thompson (2024); early-stage AI Futures coding automation</td>
<td>This is the complementarity / uplift box, where AI raises progress per dollar or per researcher without immediately replacing everybody.</td>
</tr>
<tr class="odd">
<td><strong>AI replaces low-quality R&amp;D workers first</strong></td>
<td><strong>No clean formal model among these</strong>; closest is AI Futures’ top-vs-median milestone language</td>
<td>I would leave this as “not really modeled yet” rather than force one of these papers into the box. AI Futures comes closest rhetorically, but it is not a true heterogeneous-worker replacement model. ([AI Futures][4])</td>
</tr>
<tr class="even">
<td><strong>Other mechanisms</strong></td>
<td>AI improves research taste (AI Futures); increases digital-worker supply per automated task (GATE); raises cross-sector spillovers (Davidson et al.); raises R&amp;D capital intensity (Besiroglu et al.)</td>
<td>These are important because they are not just “more tasks automated”; they change the mapping from capability to research output. ([AI Futures][4])</td>
</tr>
</tbody>
</table>
<section id="jones1995rd-rd-based-models-of-economic-growth" class="level2">
<h2 class="anchored" data-anchor-id="jones1995rd-rd-based-models-of-economic-growth"><span class="citation" data-cites="jones1995rd">Charles I. Jones (<a href="#ref-jones1995rd" role="doc-biblioref">1995</a>)</span> “R&amp;D-Based Models of Economic Growth”</h2>
<p>I’ll use the notation from <span class="citation" data-cites="jones2022semiendogenous">Charles I. Jones (<a href="#ref-jones2022semiendogenous" role="doc-biblioref">2022</a>)</span>: <span class="math display">\[\begin{aligned}
    Y_t &amp;= A_t^\sigma L_{yt}
        &amp;&amp; \text{(final good)} \\
    \frac{\dot{A_t}}{A_t} &amp;= R_t^\lambda A_t^{-\beta}
        &amp;&amp; \text{(ideas)} \\
    R_t+L_{yt} &amp;= L_t
        &amp;&amp; \text{(resource constraint)} \\
    L_t &amp;= L_0 e^{nt}
        &amp;&amp; \text{(population growth)} \\
    R_t &amp;= \bar{s}L_t
        &amp;&amp; \text{(allocation)}
\end{aligned}
\]</span></p>
<p>He also says he’ll sometimes write <span class="math inline">\(\dot{A}_t=R^\gamma_t A_t^\psi\)</span>.</p>
<blockquote class="blockquote">
<p>“The parameter <span class="math inline">\(\lambda\)</span> allows for thepossibility of duplicatione ffects,so that doubling the number of researchers at a point in time may potentially less than double the innovation rate; however, any λ&gt;0, including λ=1, is allowed.”</p>
</blockquote>
<blockquote class="blockquote">
<p>“The parameter β &gt; 0 captures the rate at which ideas—that is,proportional improvements in productivity—are getting harder to find.</p>
</blockquote>
<p>On balanced growth path: <span class="math display">\[g_y = \sigma g_A = \frac{\lambda\sigma}{\beta}n=\gamma n\]</span></p>
<p>On knife edge assumptions: he says the root of all exponential growth is exponential population growth (but seems a bit fishy).</p>
<p>Estimates of parameters:</p>
<ul>
<li>p136: <span class="math inline">\(\gamma = 1/3\)</span>, so output growth is 1/3 growth in ideas. He also predicts that long-run growth is much lower.</li>
</ul>
<p>Description of <span class="citation" data-cites="aghion2019artificial">Aghion, Jones, and Jones (<a href="#ref-aghion2019artificial" role="doc-biblioref">2019</a>)</span>. Adjust the ideas production function:</p>
<p><span class="math display">\[\dot{A}_t=A_t^{1-\beta}R_t^{1-\alpha}K_t^{\alpha}\]</span></p>
<p>with constant capital-output ratio you get: <span class="math display">\[\dot{A}_t=\kappa A_t^{1-(\beta-\alpha)}L_t\]</span></p>
<blockquote class="blockquote">
<p>“if the fraction of tasks that are automated (α) rises to reach the rate at which ideas are getting harder to find (β), we get a singularity! In particular, once α ≥ β, the model exhibits sufficiently strong increasing returns that there is no balanced growth path. Instead, the growth rate rises rapidly over time and the economy reaches infinite knowledge and income in finite time,assuming that is possible.”</p>
</blockquote>
</section>
<section id="aghion2019artificial" class="level2">
<h2 class="anchored" data-anchor-id="aghion2019artificial"><span class="citation" data-cites="aghion2019artificial">Aghion, Jones, and Jones (<a href="#ref-aghion2019artificial" role="doc-biblioref">2019</a>)</span></h2>
<p>Setup:</p>
<p><span class="math display">\[\begin{aligned}
         Y_t &amp;= A_t^{\sigma} K_t^{\alpha} L^{1-\alpha} \\
         \dot A_t &amp;= K_t^{\beta} S^{\lambda} A_t^{\phi}
      \end{aligned}
\]</span></p>
<p>Implications / thresholds:</p>
<ul>
<li>In this notation, <span class="math inline">\(\alpha\)</span> is the capital exponent in goods production and <span class="math inline">\(\beta\)</span> is the capital exponent in idea production; the “ideas getting harder to find” term is <span class="math inline">\(\phi &lt; 1\)</span>, not Jones’s <span class="math inline">\(\beta\)</span>.</li>
<li>In the paper’s task-automation framing, more automation raises the role of capital in both sectors, which can raise the long-run growth rate by making research effort more accumulable.</li>
<li>The paper distinguishes Type I growth explosions, where growth rates rise without bound but remain finite at each date, from Type II explosions, where output becomes infinite in finite time.</li>
<li>Type I condition in their examples: full automation of goods production. Once all goods tasks are automated, the goods sector becomes an AK-style economy, <span class="math inline">\(Y_t = A_tK_t\)</span>, and with ongoing technological progress the growth rate <span class="math inline">\(g_Y = g + sA_t\)</span> rises without bound.</li>
<li>Type II condition in their Example 2: full automation of ideas production. In their one-dimensional analogue this becomes <span class="math inline">\(\dot{A}_t = A_t^{1+\phi}\)</span>, so explosive growth requires <span class="math inline">\(\phi&gt;0\)</span>.</li>
<li>Type II can also arise without full automation in their Cobb-Douglas Example 3, where a key “constant returns to accumulable factors” parameter exceeds one.</li>
</ul>
<table class="caption-top table">
<colgroup>
<col style="width: 6%">
<col style="width: 93%">
</colgroup>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\alpha\)</span></td>
<td>capital exponent in goods production.</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\beta\)</span></td>
<td>capital exponent in idea production.</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\lambda\)</span></td>
<td>elasticity of idea production with respect to research labor.</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\phi\)</span></td>
<td>standing-on-shoulders term in the paper’s notation, with Jones-style harder-to-find parameter <span class="math inline">\(\beta_{\text{Jones}} = 1-\phi\)</span>.</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\sigma\)</span></td>
<td>role of nonrival ideas in final output.</td>
</tr>
<tr class="even">
<td></td>
<td></td>
</tr>
</tbody>
</table>
</section>
<section id="davidson2021could" class="level2">
<h2 class="anchored" data-anchor-id="davidson2021could"><span class="citation" data-cites="davidson2021could">Davidson (<a href="#ref-davidson2021could" role="doc-biblioref">2021</a>)</span></h2>
<p>Davidson writes idea production in <span class="math inline">\(\phi\)</span>-notation rather than Jones <span class="math inline">\(\beta\)</span>-notation, so the mapping is <span class="math inline">\(\beta = 1-\phi\)</span>.</p>
<ul>
<li>Aggregate innovation: <span class="math inline">\(\phi=-2.1 \Rightarrow \beta \approx 3.1\)</span>.</li>
<li>Hardware: <span class="math inline">\(\phi=0.8 \Rightarrow \beta \approx 0.2\)</span>.</li>
<li>ML software: <span class="math inline">\(\phi=0.85 \Rightarrow \beta \approx 0.15\)</span>.</li>
</ul>
<p>This is one of the main routes by which very low software <span class="math inline">\(\beta\)</span> enters AI-takeoff discussions. But it is best read as importing earlier subsector estimates in <span class="math inline">\(\phi\)</span>-notation, not as a fresh direct estimate of frontier-AI-lab <span class="math inline">\(\beta\)</span>.</p>
</section>
<section id="erdil2024explosive-explosive-growth-from-ai-automation-a-review-of-the-arguments" class="level2">
<h2 class="anchored" data-anchor-id="erdil2024explosive-explosive-growth-from-ai-automation-a-review-of-the-arguments"><span class="citation" data-cites="erdil2024explosive">Erdil and Besiroglu (<a href="#ref-erdil2024explosive" role="doc-biblioref">2024</a>)</span> “Explosive growth from AI automation: A review of the arguments”</h2>
<blockquote class="blockquote">
<p>“Bloom et al.&nbsp;2020, which provides us perhaps with the best estimates of the extent to which ideas get “harder to find”, estimates that λ/ϕ ≈ 0.32 for total factor productivity in the US economy. Based on this, we find that hyperbolic growth occurs with values of β as low as 1 − 0.32 = 0.68. Hence, hyperbolic growth with AI is predicted by R&amp;D-based growth models even if we do not strictly accept the conclusion of the replication argument that β = 1. This point, that avoiding increasing returns to scale is difficult to avoid even when ideas get “harder to find” over time, has been noted elsewhere, notably by Davidson 2021. Indeed, this outcome is consistent with fairly conservative assumption on there being decreasing returns on inputs to final goods production.”</p>
</blockquote>
</section>
<section id="erdil2024estimating-estimating-idea-production-a-methodological-survey" class="level2">
<h2 class="anchored" data-anchor-id="erdil2024estimating-estimating-idea-production-a-methodological-survey"><span class="citation" data-cites="erdil2024estimating">Erdil, Besiroglu, and Ho (<a href="#ref-erdil2024estimating" role="doc-biblioref">2024</a>)</span> “Estimating Idea Production: A Methodological Survey”</h2>
<p><span class="math display">\[\begin{aligned}
    Y &amp;= AK^\alpha \\
    \dot{K} &amp;\propto Y &amp;&amp; \text{(constant savings rate)}\\
    \dot{A}/A &amp;\propto A^{-\beta}K^\lambda &amp;&amp; \text{(productivity growth)}
\end{aligned}
\]</span></p>
<p>Parameters:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 13%">
<col style="width: 86%">
</colgroup>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\alpha\)</span></td>
<td>capital elasticity in final output.</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\lambda\)</span></td>
<td>elasticity of productivity growth with respect to R&amp;D input.</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\beta\)</span></td>
<td>ideas-get-harder-to-find parameter.</td>
</tr>
<tr class="even">
<td><span class="math inline">\(r=\lambda/\beta\simeq 1\)</span></td>
<td>the object the paper argues is usually identified more robustly than either numerator or denominator on its own.</td>
</tr>
<tr class="odd">
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p>Implications / thresholds:</p>
<ul>
<li>The paper’s main methodological lesson is that much of this literature identifies <span class="math inline">\(r=\lambda/\beta\)</span> more cleanly than it identifies <span class="math inline">\(\beta\)</span> itself.</li>
<li>In their simple growth setup, you get steady-state growth if and only if <span class="math inline">\(\lambda/\beta+\alpha=1\)</span>.</li>
<li>You get hyperbolic growth if <span class="math inline">\(\lambda/\beta+\alpha&gt;1\)</span>.</li>
</ul>
<p>In the best high-frequency software case study they discuss, Stockfish, the central estimate is <span class="math inline">\(r \approx 0.83\)</span> with standard error <span class="math inline">\(0.15\)</span>. For sparser domains, their Bayesian posterior medians are:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 27%">
<col style="width: 11%">
<col style="width: 21%">
<col style="width: 19%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>domain</th>
<th>doubling time</th>
<th>median <span class="math inline">\(r=\lambda/\beta\)</span></th>
<th>β</th>
<th>λ</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Stockfish</td>
<td></td>
<td>0.83</td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Computer vision, 2012-2022</td>
<td>9 months</td>
<td>1.44</td>
<td>0.985 (0.224 to 4.050)</td>
<td>1.410 (0.290 to 6.021)</td>
</tr>
<tr class="odd">
<td>RL sample efficiency, 2015-2019</td>
<td>11 months</td>
<td>1.58</td>
<td>1.023 (0.212 to 3.914)</td>
<td>1.482 (0.266 to 6.650)</td>
</tr>
<tr class="even">
<td>SAT solvers, 1997-2018</td>
<td>2 years</td>
<td>3.54</td>
<td>0.648 (0.139 to 2.891)</td>
<td>2.143 (0.387 to 11.312)</td>
</tr>
<tr class="odd">
<td>Linear programming, 1998-2018</td>
<td>6 years</td>
<td>1.08</td>
<td>1.290 (0.254 to 4.953)</td>
<td>1.259 (0.222 to 5.772)</td>
</tr>
</tbody>
</table>
</section>
<section id="kokotajlo2025aifuturesmodel-ai-futures-model" class="level2">
<h2 class="anchored" data-anchor-id="kokotajlo2025aifuturesmodel-ai-futures-model"><span class="citation" data-cites="kokotajlo2025aifuturesmodel">Kokotajlo et al. (<a href="#ref-kokotajlo2025aifuturesmodel" role="doc-biblioref">2025</a>)</span> AI futures model</h2>
<p>More complicated!</p>
</section>
<section id="ho2025explosionexperiments-the-software-intelligence-explosion-debate-needs-experiments" class="level2">
<h2 class="anchored" data-anchor-id="ho2025explosionexperiments-the-software-intelligence-explosion-debate-needs-experiments"><span class="citation" data-cites="ho2025explosionexperiments">Ho and Whitfill (<a href="#ref-ho2025explosionexperiments" role="doc-biblioref">2025</a>)</span> “The software intelligence explosion debate needs experiments”</h2>
<p>Equations:</p>
<p><span class="math display">\[\dot{A} = A^{1-\beta}F(L,K)^\lambda\]</span></p>
<p>If research automation makes effective research input proportional to algorithmic progress itself, so that <span class="math inline">\(F(L,K)\propto cA\)</span>, then</p>
<p><span class="math display">\[\dot{A} \propto A^{\lambda+1-\beta}.\]</span></p>
<p>Implications / thresholds:</p>
<ul>
<li>In this setup, the key threshold is <span class="math inline">\(r\equiv\frac{\lambda}{\beta}\)</span>.</li>
<li>You get explosive growth if <span class="math inline">\(r&gt;1\)</span>.</li>
<li>In their domain-level estimates, the NLP / language-model proxy is the strongest case for <span class="math inline">\(r&gt;1\)</span>, but the uncertainty intervals are still very wide.</li>
<li>In their OpenAI 2022-2025 back-of-the-envelope exercise, the central estimate is <span class="math inline">\(r \approx 0.96\)</span>, and under a Cobb-Douglas bottleneck story the relevant object becomes <span class="math inline">\((1-\epsilon_K)\lambda/\beta\)</span>, which pushes the effective value further below <span class="math inline">\(1\)</span>.</li>
</ul>
<p>This is the cleanest direct <span class="math inline">\(\beta\)</span> estimation exercise I have found that is actually about AI-ish domains rather than aggregate innovation or imported hardware benchmarks. The key caveat is that the intervals are extremely wide.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 20%">
<col style="width: 17%">
<col style="width: 24%">
<col style="width: 24%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>computer vision</th>
<th>reinforcement learning</th>
<th>natural language processing proxy</th>
<th>OpenAI 2022-2025 back-of-envelope</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\beta\)</span></td>
<td>1.302 (90% CrI 0.269-5.571)</td>
<td>1.299 (0.241-5.581)</td>
<td>1.586 (0.322-7.148)</td>
<td>not separately identified</td>
</tr>
<tr class="even">
<td><span class="math inline">\(r=\lambda/\beta\)</span></td>
<td>1.262</td>
<td>1.201</td>
<td>1.892</td>
<td>about 0.96</td>
</tr>
</tbody>
</table>
<table class="caption-top table">
<colgroup>
<col style="width: 10%">
<col style="width: 89%">
</colgroup>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\beta\)</span></td>
<td>the ideas-get-harder-to-find parameter for AI software.</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\lambda\)</span></td>
<td>the elasticity of progress with respect to effective research input.</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\epsilon_K\)</span></td>
<td>the elasticity of research input with respect to experiment compute in the Cobb-Douglas bottleneck variant.</td>
</tr>
</tbody>
</table>
<p>Their proxies for software quality are based on measures of training compute efficiency. They note that if <span class="math inline">\(A\)</span> is inference compute efficiency, the augmentation equation holds exactly; if <span class="math inline">\(A\)</span> is training compute efficiency, it requires an additional linearity assumption connecting training efficiency to effective AI researchers.</p>
</section>
<section id="erdil2025automatingrd-most-ai-value-will-come-from-broad-automation-not-from-rd" class="level2">
<h2 class="anchored" data-anchor-id="erdil2025automatingrd-most-ai-value-will-come-from-broad-automation-not-from-rd"><span class="citation" data-cites="erdil2025automatingrd">Erdil and Barnett (<a href="#ref-erdil2025automatingrd" role="doc-biblioref">2025</a>)</span> “Most AI value will come from broad automation, not from R&amp;D”</h2>
<p>They give arguments for why AI R&amp;D will be bottlenecked by experiment compute:</p>
<blockquote class="blockquote">
<p>“By default, a software-only or software-biased singularity should be treated as an unlikely outcome rather than a likely one.”</p>
</blockquote>
<blockquote class="blockquote">
<p>“If the two inputs are indeed complementary, any software-driven acceleration could only last until we become bottlenecked on compute and end up having to do the physical work of obtaining more GPUs in order to run more experiments.”</p>
</blockquote>
<blockquote class="blockquote">
<p>“Just as one example, Oberfield and Raval (2014) estimate that the elasticity of substitution between labor and capital in the US manufacturing sector is 0.7, and this is already strong enough for any “software-only singularity” to fizzle out after less than an order of magnitude of improvement in efficiency.”</p>
</blockquote>
</section>
<section id="eth2025willairdautomati" class="level2">
<h2 class="anchored" data-anchor-id="eth2025willairdautomati"><span class="citation" data-cites="eth2025willairdautomati">Eth and Davidson (<a href="#ref-eth2025willairdautomati" role="doc-biblioref">2025</a>)</span></h2>
<blockquote class="blockquote">
<p>“More specifically, r gives the number of times software doubles for each time the cumulative work on software R&amp;D doubles … There are a few reasons to think that r is currently above 1:”</p>
</blockquote>
<p>Implications / thresholds:</p>
<ul>
<li>The paper’s question is whether current software R&amp;D has <span class="math inline">\(r&gt;1\)</span>, since that is the relevant threshold for a software intelligence explosion in the simplest Jones-style setup.</li>
<li>The nearby empirical anchors are also mostly estimates of <span class="math inline">\(r\)</span>: in the best high-frequency software case study, Stockfish, the central estimate is <span class="math inline">\(r \approx 0.83\)</span> with standard error <span class="math inline">\(0.15\)</span>; in sparser software domains the Bayesian posterior medians are about <span class="math inline">\(1.44\)</span> for computer vision, <span class="math inline">\(1.58\)</span> for RL sample efficiency, <span class="math inline">\(3.54\)</span> for SAT, and <span class="math inline">\(1.08\)</span> for linear programming <span class="citation" data-cites="erdil2024estimating">Erdil, Besiroglu, and Ho (<a href="#ref-erdil2024estimating" role="doc-biblioref">2024</a>)</span>.</li>
</ul>
<p>Those numbers matter for whether recursive improvement crosses the critical threshold, but they do not separately identify <span class="math inline">\(\beta\)</span> unless we also know <span class="math inline">\(\lambda\)</span>.</p>
</section>
<section id="davidson2025howquickandbigwo" class="level2">
<h2 class="anchored" data-anchor-id="davidson2025howquickandbigwo"><span class="citation" data-cites="davidson2025howquickandbigwo">Davidson and Houlden (<a href="#ref-davidson2025howquickandbigwo" role="doc-biblioref">2025</a>)</span></h2>
<p><span class="math display">\[
\begin{aligned}
\dot S(L, C) &amp;= a [R(L, C)]^\lambda S^{1-\beta} &amp;&amp; \text{(Software L.O.M.)} \\
R(L, C) &amp;= (bL)^\alpha (cC)^{1-\alpha} &amp;&amp; \text{(Research Input)} \\
L &amp;= dS &amp;&amp; \text{(Cognitive Labour)}
\end{aligned}
\]</span></p>
<p>Parameters:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 6%">
<col style="width: 93%">
</colgroup>
<tbody>
<tr class="odd">
<td><span class="math inline">\(S\)</span></td>
<td>is the level of AI software.</td>
</tr>
<tr class="even">
<td><span class="math inline">\(L\)</span></td>
<td>is the cognitive labour used for improving software.</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(C\)</span></td>
<td>is compute for experiments, assumed to be constant.</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\lambda\)</span></td>
<td>captures “stepping on toes,” whereby there are diminishing returns to applying more research effort in parallel (“nine women can’t make a baby in a month”).</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\beta \approx 0.25\)</span></td>
<td>captures the idea that software improvements get harder to find as software improves.</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\alpha\)</span></td>
<td>captures the diminishing returns of cognitive labour in improving software.</td>
</tr>
<tr class="odd">
<td>r=/</td>
<td></td>
</tr>
</tbody>
</table>
<p>Implications / thresholds:</p>
<ul>
<li>The key threshold is <span class="math inline">\(r=\lambda\alpha/\beta\)</span>.</li>
<li>The paper calibrates primarily in terms of <span class="math inline">\(p\)</span> and <span class="math inline">\(r\)</span>, not by directly estimating <span class="math inline">\(\beta\)</span>.</li>
<li>Their reported medians are <span class="math inline">\(p=0.3\)</span> and <span class="math inline">\(r=1.2\)</span>, and one representative decomposition is <span class="math inline">\(\alpha=0.5\)</span>, <span class="math inline">\(\lambda=0.6\)</span>, and <span class="math inline">\(\beta=0.25\)</span>.</li>
</ul>
<p>then they note <span class="math inline">\(r=\lambda \alpha / \beta\)</span>, and this is critical</p>
</section>
<section id="kokotajlo2025aifuturesmodel-ai-futures-model-dec-2025-update" class="level2">
<h2 class="anchored" data-anchor-id="kokotajlo2025aifuturesmodel-ai-futures-model-dec-2025-update"><span class="citation" data-cites="kokotajlo2025aifuturesmodel">Kokotajlo et al. (<a href="#ref-kokotajlo2025aifuturesmodel" role="doc-biblioref">2025</a>)</span> “AI Futures Model: Dec 2025 Update”</h2>
<blockquote class="blockquote">
<p>“Davidson and Houlden focuses primarily on trends of how much more efficiently AIs have been able to achieve the same performance when determining whether there will be an SIE. Meanwhile, we focus on estimates of the quality of AIs’ research taste, i.e.&nbsp;how good the AI is at choosing research directions, selecting and interpreting experiments, etc. We think that focusing on research taste quality is a more useful lens from which to view a potential SIE. If there’s an SIE we expect that it will primarily be driven by improvements in research taste.”</p>
</blockquote>
<p>Superhuman AI Researcher = “An AI system that can do the job of the best human AI researcher but 30x faster and with 30x more agents, as defined above in the superhuman coder milestone. It must have enough diversity of expertise to on average do the same for other top researchers with complementary skills.”</p>
</section>
<section id="davidson2026automatingairesearch-when-does-automating-research-produce-explosive-growth" class="level2">
<h2 class="anchored" data-anchor-id="davidson2026automatingairesearch-when-does-automating-research-produce-explosive-growth"><span class="citation" data-cites="davidson2026automatingairesearch">Davidson et al. (<a href="#ref-davidson2026automatingairesearch" role="doc-biblioref">2026</a>)</span> “When Does Automating Research Produce Explosive Growth?”</h2>
<p>Summary: once you automate a sufficient number of tasks (i.e.&nbsp;do them with capital) then this will kick-off an intelligence explosion.</p>
<p><span class="math display">\[\begin{aligned}
    \dot{S}(L,C) &amp;= a [R(L,C)]^\lambda S^{1-\beta_S} &amp;&amp; \text{(software law of motion)} \\
    R(L,C) &amp;= (bL)^\alpha (cC)^{1-\alpha} &amp;&amp; \text{(Research Input)} \\
    L &amp;= dS &amp;&amp; \text{(Cognitive Labour)}
\end{aligned}
\]</span></p>
<p>Parameters:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 83%">
</colgroup>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\beta_S \approx 1\)</span></td>
<td>software ideas-get-harder-to-find parameter, citing <span class="citation" data-cites="ho2025explosionexperiments">Ho and Whitfill (<a href="#ref-ho2025explosionexperiments" role="doc-biblioref">2025</a>)</span> and <span class="citation" data-cites="erdil2024estimating">Erdil, Besiroglu, and Ho (<a href="#ref-erdil2024estimating" role="doc-biblioref">2024</a>)</span>.</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\beta_H \approx 0.2\)</span></td>
<td>hardware ideas-get-harder-to-find parameter.</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\beta_A \approx 3.1\)</span></td>
<td>aggregate innovation ideas-get-harder-to-find parameter.</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\alpha\)</span></td>
<td>labor elasticity in the research-input aggregator.</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\lambda\)</span></td>
<td>stepping-on-toes / parallelization parameter.</td>
</tr>
<tr class="even">
<td><span class="math inline">\(r_S\approx 1\)</span></td>
<td></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(r_H\approx 5\)</span></td>
<td></td>
</tr>
<tr class="even">
<td><span class="math inline">\(r_A\approx 0.32\)</span></td>
<td></td>
</tr>
</tbody>
</table>
<p>Critical condition for explosive growth:</p>
<p><span class="math display">\[
    \utt{f_Y}{share output}{tasks automated} +
    \utt{f_S}{share software}{tasks automated}\frac{1}{\beta_S} +
    \utt{f_H}{share hardware}{tasks automated}\frac{1}{\beta_H} +
    \utt{f_A}{share innovation}{tasks automated}\frac{1}{\alpha}\frac{1}{\beta_A}
    &gt;1
\]</span></p>
<ul>
<li>Basic model:
<ul>
<li>If <span class="math inline">\(\dot{S}_t=S_t^{1-\beta}\)</span>, so you get explosion if <span class="math inline">\(\beta&lt;0\)</span>, steady-state growth if <span class="math inline">\(\beta=0\)</span>, and gradual slowing if <span class="math inline">\(\beta&gt;1\)</span>.</li>
<li>Now if you start automating inputs, the effective exponent gradually gets higher.</li>
</ul></li>
<li>Multi-sector version.
<ul>
<li>You gradually automate some of the things, so they can be done with capital.</li>
<li>You have spillovers between different processes.</li>
</ul></li>
<li>Estimates of <span class="math inline">\(\beta\)</span>:
<ul>
<li>Bloom overall <span class="math inline">\(\beta=3\)</span></li>
<li>For software R&amp;D they estimate <span class="math inline">\(\beta=3\)</span></li>
<li>they say in software <span class="math inline">\(\beta=0.1\)</span></li>
</ul></li>
<li>Questions:
<ul>
<li>Any historical domain where we’ve seen regimes of <span class="math inline">\(\beta&lt;0\)</span>?, &amp; so explosion.</li>
</ul></li>
</ul>
<p>Implications / thresholds:</p>
<ul>
<li><p>Q: how to think about the growth effect of uplift vs automation?</p></li>
<li><p>It seems to me AI typically makes things effectively <em>free</em>, rather than being bottlenecked by capital. I think this is a problem for Cobb-Douglas production.</p></li>
</ul>
</section>
<section id="kokotajlo2025aifuturesmodel-ai-futures-model" class="level2">
<h2 class="anchored" data-anchor-id="kokotajlo2025aifuturesmodel-ai-futures-model"><span class="citation" data-cites="kokotajlo2025aifuturesmodel">Kokotajlo et al. (<a href="#ref-kokotajlo2025aifuturesmodel" role="doc-biblioref">2025</a>)</span> AI futures model</h2>
<p>https://www.timelinesmodel.com</p>
<p>They assume AI automates some fraction of R&amp;D tasks, proportional to the time horizon.</p>
</section>
<section id="kwa2026simpleraitimelines-tkwa-model" class="level2">
<h2 class="anchored" data-anchor-id="kwa2026simpleraitimelines-tkwa-model"><span class="citation" data-cites="kwa2026simpleraitimelines">Kwa (<a href="#ref-kwa2026simpleraitimelines" role="doc-biblioref">2026</a>)</span> tkwa&nbsp; model</h2>
<p>Short: AI automates some fraction of R&amp;D tasks, which causes an effective multiplier on R&amp;D labor: “parallel uplift and 1/(1-f) are equivalent in the simple model”.</p>
<p>https://github.com/tkwa/ai-takeoff-model/blob/main/notes.md https://www.lesswrong.com/posts/uy6B5rEPvcwi55cBK/research-note-a-simpler-ai-timelines-model-predicts-99-ai-r</p>
<p><span class="math display">\[\begin{aligned}
   S'(t) &amp;= R(t) S^{1 - \beta} = \left(\frac L {1-f}\right)^\alpha C^\zeta S^{1 - \beta}\\
   f(t) &amp;= \sigma(v(\log C(t)S(t) - \log E_{hac}))
\end{aligned}
\]</span></p>
<p>My simpler version:</p>
<p><span class="math display">\[\begin{aligned}
   \dot{S}  &amp;= L^\alpha C^\gamma S^{1-\beta} \\
\end{aligned}
\]</span></p>
<p>We can show:</p>
<p><span class="math display">\[S^{\beta} = S_0^{\beta} + \frac{\beta\,L_0^\alpha C_0^\gamma}{\alpha g_L+\gamma g_C}\Big(e^{(\alpha g_L+\gamma g_C)t}-1\Big).\]</span></p>
<p>In the limit we get <span class="math inline">\(g_s=\frac{\alpha g_L+\gamma g_C}{\beta}\)</span></p>
</section>
<section id="david-rein-notes" class="level2">
<h2 class="anchored" data-anchor-id="david-rein-notes">David Rein notes</h2>
<ul>
<li>Model:
<ul>
<li><span class="math inline">\(dA = Q^q A^{1-\beta}\)</span></li>
<li><span class="math inline">\(Q\)</span> is the quality of cognitive labour, measured in units of time horizon—this is our AI researcher (e.g.&nbsp;Opus 4.5, GPT-5.2, Gemini 3)</li>
<li><span class="math inline">\(A\)</span> is the current level of algorithms, also measured in units of time horizon (e.g.&nbsp;GPT-2, GPT-3, Pythia, etc.)</li>
<li><span class="math inline">\(\beta\)</span> is the ideas getting harder to find parameter</li>
<li>The explosion condition here is <span class="math inline">\(q &gt; \beta\)</span></li>
<li>(Must also assume that <span class="math inline">\(Q=cA\)</span>.</li>
</ul></li>
<li><a href="https://docs.google.com/document/d/16Ugl7g3GL1Ao9-3UluRENp6e9UeEMAqhh5jgXDi3kjo/edit?tab=t.a5tu3xadb63o#heading=h.ribcf6q6wbps">doc</a></li>
</ul>
<hr>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR
    subgraph Inputs["Inputs"]
        L["Labor&lt;br/&gt;(growing 2×)"]
        C["Compute&lt;br/&gt;(growing 3×)"]
    end
    
    subgraph RnD["AI R&amp;D"]
        E["Efficiency&lt;br/&gt;(growing 5×)"]
    end
    
    subgraph Capabilities["Capabilities"]
        EC["Effective&lt;br/&gt;Compute"]
        TH["Time Horizon"]
    end
    
    subgraph Feedback["Feedback Loop"]
        A["Automation"]
    end
    
    L --&gt;|"α = 0.25"| E
    C --&gt;|"ζ = 0.6"| E
    E --&gt;|"β = 0.5&lt;br/&gt;(self-improving)"| E
    C --&gt; EC
    E --&gt; EC
    EC --&gt; TH
    TH --&gt;|"ν = 1/3"| A
    A --&gt;|"augments"| L
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR
  labor --&gt; algorithms
  RD_compute["R&amp;D compute"] --&gt; algorithms
  algorithms --&gt; intelligence
  training_compute --&gt; intelligence
  data --&gt; intelligence
  intelligence --&gt;|??| economic_value["economic value"]
  intelligence --&gt;|??| RD
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>



</section>
</section>


<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-aghion2019artificial" class="csl-entry" role="listitem">
Aghion, Philippe, Benjamin F. Jones, and Charles I. Jones. 2019. <span>“Artificial Intelligence and Economic Growth.”</span> In <em>The Economics of Artificial Intelligence: An Agenda</em>, edited by Ajay Agrawal, Joshua Gans, and Avi Goldfarb, 237–90. Chicago: University of Chicago Press. <a href="https://doi.org/10.7208/9780226613475-011">https://doi.org/10.7208/9780226613475-011</a>.
</div>
<div id="ref-amodei2018aiandcompute" class="csl-entry" role="listitem">
Amodei, Dario, and Danny Hernandez. 2018. <span>“AI and Compute.”</span> <a href="https://openai.com/index/ai-and-compute/">https://openai.com/index/ai-and-compute/</a>.
</div>
<div id="ref-anthropic2025claude_work" class="csl-entry" role="listitem">
Anthropic. 2025. <span>“Claude at Work: How Anthropic Uses Claude Code Internally.”</span> <a href="https://assets.anthropic.com/m/6cd21f7d4f82afcb/original/Claude-at-Work-Survey.pdf" class="uri">https://assets.anthropic.com/m/6cd21f7d4f82afcb/original/Claude-at-Work-Survey.pdf</a>.
</div>
<div id="ref-byrnes2026naturellmalgorithmicprogress" class="csl-entry" role="listitem">
Byrnes, Steven. 2026. <span>“The Nature of <span>LLM</span> Algorithmic Progress (V2).”</span> <a href="https://www.lesswrong.com/posts/sGNFtWbXiLJg2hLzK/the-nature-of-llm-algorithmic-progress-v2">https://www.lesswrong.com/posts/sGNFtWbXiLJg2hLzK/the-nature-of-llm-algorithmic-progress-v2</a>.
</div>
<div id="ref-davidson2021could" class="csl-entry" role="listitem">
Davidson, Tom. 2021. <span>“Could Advanced AI Drive Explosive Economic Growth.”</span> <em>Open Philanthropy</em> 25. <a href="https://www.openphilanthropy.org/research/could-advanced-ai-drive-explosive-economic-growth">https://www.openphilanthropy.org/research/could-advanced-ai-drive-explosive-economic-growth</a>.
</div>
<div id="ref-davidson2026automatingairesearch" class="csl-entry" role="listitem">
Davidson, Tom, Basil Halperin, Thomas Houlden, and Anton Korinek. 2026. <span>“When Does Automating AI Research Produce Explosive Growth?”</span> <a href="https://www.basilhalperin.com/papers/shs.pdf">https://www.basilhalperin.com/papers/shs.pdf</a>.
</div>
<div id="ref-davidson2025howquickandbigwo" class="csl-entry" role="listitem">
Davidson, Tom, and Tom Houlden. 2025. <span>“How Quick and Big Would a Software Intelligence Explosion Be?”</span> <a href="https://www.forethought.org/research/how-quick-and-big-would-a-software-intelligence-explosion-be">https://www.forethought.org/research/how-quick-and-big-would-a-software-intelligence-explosion-be</a>.
</div>
<div id="ref-epoch2025computescaling" class="csl-entry" role="listitem">
Edelman, Yafah, and Anson Ho. 2025. <span>“Compute Scaling Will Slow down Due to Increasing Lead Times.”</span> <a href="https://epoch.ai/gradient-updates/compute-scaling-will-slow-down-due-to-increasing-lead-times/">https://epoch.ai/gradient-updates/compute-scaling-will-slow-down-due-to-increasing-lead-times/</a>.
</div>
<div id="ref-efrati2025openaicomputingcostproblem" class="csl-entry" role="listitem">
Efrati, Amir, and Sri Muppidi. 2025. <a href="https://www.theinformation.com/articles/openais-350-billion-computing-cost-problem">https://www.theinformation.com/articles/openais-350-billion-computing-cost-problem</a>.
</div>
<div id="ref-epoch2025trainingcomputefrontier" class="csl-entry" role="listitem">
Epoch AI. 2025a. <span>“Training Compute of Frontier AI Models Grows by 4-5x Per Year.”</span> <a href="https://epoch.ai/blog/training-compute-of-frontier-ai-models-grows-by-4-5x-per-year">https://epoch.ai/blog/training-compute-of-frontier-ai-models-grows-by-4-5x-per-year</a>.
</div>
<div id="ref-EpochAIModels2025" class="csl-entry" role="listitem">
———. 2025b. <span>“Data on AI Models.”</span> <a href="https://epoch.ai/data/ai-models/">https://epoch.ai/data/ai-models/</a>.
</div>
<div id="ref-epoch2026computetrendpost2010" class="csl-entry" role="listitem">
———. 2026a. <span>“The Training Compute of Notable AI Models Has Been Doubling Roughly Every Six Months.”</span> <a href="https://epoch.ai/data-insights/compute-trend-post-2010">https://epoch.ai/data-insights/compute-trend-post-2010</a>.
</div>
<div id="ref-EpochAITrends2026" class="csl-entry" role="listitem">
———. 2026b. <span>“Trends in Artificial Intelligence.”</span> <a href="https://epoch.ai/trends">https://epoch.ai/trends</a>.
</div>
<div id="ref-erdil2024explosive" class="csl-entry" role="listitem">
Erdil, Ege, and Tamay Besiroglu. 2024. <span>“Explosive Growth from AI Automation: A Review of the Arguments.”</span> <a href="https://arxiv.org/abs/2309.11690">https://arxiv.org/abs/2309.11690</a>.
</div>
<div id="ref-erdil2024estimating" class="csl-entry" role="listitem">
Erdil, Ege, Tamay Besiroglu, and Anson Ho. 2024. <span>“Estimating Idea Production: A Methodological Survey,”</span> May. <a href="https://doi.org/10.2139/ssrn.4814445">https://doi.org/10.2139/ssrn.4814445</a>.
</div>
<div id="ref-erdil2025gate" class="csl-entry" role="listitem">
Erdil, Ege, Andrei Potlogea, Tamay Besiroglu, Edu Roldan, Anson Ho, Jaime Sevilla, Matthew Barnett, Matej Vrzla, and Robert Sandler. 2025. <span>“GATE: An Integrated Assessment Model for AI Automation.”</span> <em>arXiv Preprint arXiv:2503.04941</em>. <a href="https://arxiv.org/pdf/2503.04941.pdf">https://arxiv.org/pdf/2503.04941.pdf</a>.
</div>
<div id="ref-eth2025willairdautomati" class="csl-entry" role="listitem">
Eth, Daniel, and Tom Davidson. 2025. <span>“Will AI r&amp;d Automation Cause a Software Intelligence Explosion?”</span> <a href="https://www.forethought.org/research/will-ai-r-and-d-automation-cause-a-software-intelligence-explosion">https://www.forethought.org/research/will-ai-r-and-d-automation-cause-a-software-intelligence-explosion</a>.
</div>
<div id="ref-gundlach2025algorithmicprogressai" class="csl-entry" role="listitem">
Gundlach, Hans, Alex Fogelson, Jayson Lynch, Ana Trisovic, Jonathan Rosenfeld, Anmol Sandhu, and Neil Thompson. 2025. <span>“On the Origin of Algorithmic Progress in AI.”</span> <a href="https://arxiv.org/abs/2511.21622">https://arxiv.org/abs/2511.21622</a>.
</div>
<div id="ref-ho2026leastunderstooddriver" class="csl-entry" role="listitem">
Ho, Anson. 2026. <span>“The Least Understood Driver of AI Progress.”</span> <a href="https://epoch.ai/gradient-updates/the-least-understood-driver-of-ai-progress">https://epoch.ai/gradient-updates/the-least-understood-driver-of-ai-progress</a>.
</div>
<div id="ref-ho2024algorithmicprogresslm" class="csl-entry" role="listitem">
Ho, Anson, Tamay Besiroglu, Ege Erdil, David Owen, Robi Rahman, Zifan Carl Guo, David Atkinson, Neil Thompson, and Jaime Sevilla. 2024. <span>“Algorithmic Progress in Language Models.”</span> <a href="https://doi.org/10.48550/arXiv.2403.05812">https://doi.org/10.48550/arXiv.2403.05812</a>.
</div>
<div id="ref-jones2025aird" class="csl-entry" role="listitem">
Jones, Benjamin F. 2025. <span>“Artificial Intelligence in Research and Development.”</span> NBER Working Paper 34312. National Bureau of Economic Research. <a href="https://doi.org/10.3386/w34312">https://doi.org/10.3386/w34312</a>.
</div>
<div id="ref-jones1995rd" class="csl-entry" role="listitem">
Jones, Charles I. 1995. <span>“R&amp;d-Based Models of Economic Growth.”</span> <em>Journal of Political Economy</em> 103 (4): 759–84. https://doi.org/<a href="https://doi.org/10.1086/262002">https://doi.org/10.1086/262002</a>.
</div>
<div id="ref-jones2022semiendogenous" class="csl-entry" role="listitem">
Jones, Charles I. 2022. <span>“The Past and Future of Economic Growth: A Semi-Endogenous Perspective.”</span> <em>Annual Review of Economics</em> 14 (1): 125–52. <a href="https://doi.org/10.1146/annurev-economics-080521-012458">https://doi.org/10.1146/annurev-economics-080521-012458</a>.
</div>
<div id="ref-kellerjordan2026moddednanogpt" class="csl-entry" role="listitem">
Jordan, Keller, and contributors. 2026. <span>“Modded-Nanogpt.”</span> <a href="https://github.com/KellerJordan/modded-nanogpt">https://github.com/KellerJordan/modded-nanogpt</a>.
</div>
<div id="ref-karpathy2024llmcdiscussion" class="csl-entry" role="listitem">
Karpathy, Andrej. 2024. <span>“Llm.c Discussion: Reproducing <span>GPT</span>-2 in 90 Minutes for $20.”</span> <a href="https://github.com/karpathy/llm.c/discussions/481">https://github.com/karpathy/llm.c/discussions/481</a>.
</div>
<div id="ref-kokotajlo2025aifuturesmodel" class="csl-entry" role="listitem">
Kokotajlo, Daniel, Eli Lifland, Brendan Halstead, and Alex Kastner. 2025. <span>“AI Futures Model: Dec 2025 Update.”</span> <a href="https://blog.ai-futures.org/p/ai-futures-model-dec-2025-update">https://blog.ai-futures.org/p/ai-futures-model-dec-2025-update</a>.
</div>
<div id="ref-kwa2026simpleraitimelines" class="csl-entry" role="listitem">
Kwa, Thomas. 2026. <span>“Research Note: A Simpler AI Timelines Model Predicts 99% AI r&amp;d Automation in ~2032.”</span> <a href="https://www.lesswrong.com/posts/uy6B5rEPvcwi55cBK/research-note-a-simpler-ai-timelines-model-predicts-99-ai-r">https://www.lesswrong.com/posts/uy6B5rEPvcwi55cBK/research-note-a-simpler-ai-timelines-model-predicts-99-ai-r</a>.
</div>
<div id="ref-thompson2022importancecomputingpower" class="csl-entry" role="listitem">
Thompson, Neil C., Shuning Ge, and Gabriel F. Manso. 2022. <span>“The Importance of (Exponentially More) Computing Power.”</span> <a href="https://doi.org/10.48550/arXiv.2206.14007">https://doi.org/10.48550/arXiv.2206.14007</a>.
</div>
<div id="ref-whitfill2026gpt2tweet" class="csl-entry" role="listitem">
Whitfill, Parker. 2026. <span>“Post on <span>GPT</span>-2 to Nano<span>GPT</span> Efficiency Gains.”</span> <a href="https://x.com/whitfill_parker/status/2028515815268491592">https://x.com/whitfill_parker/status/2028515815268491592</a>.
</div>
<div id="ref-whitfill2025forecastingaitimehorizon" class="csl-entry" role="listitem">
Whitfill, Parker, Ben Snodin, and Joel Becker. 2025. <span>“Forecasting AI Time Horizon Under Compute Slowdowns.”</span> <a href="https://arxiv.org/abs/2511.19492">https://arxiv.org/abs/2511.19492</a>.
</div>
<div id="ref-whitfill2025bottlenecks" class="csl-entry" role="listitem">
Whitfill, Parker, and Cheryl Wu. 2025. <span>“Will Compute Bottlenecks Prevent an Intelligence Explosion?”</span> <a href="https://arxiv.org/abs/2507.23181">https://arxiv.org/abs/2507.23181</a>.
</div>
<div id="ref-you2025openaicomputespend" class="csl-entry" role="listitem">
You, Josh. 2025. <span>“Most of OpenAI’s 2024 Compute Went to Experiments.”</span> <a href="https://epoch.ai/data-insights/openai-compute-spend">https://epoch.ai/data-insights/openai-compute-spend</a>.
</div>
</div></section><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p><span class="citation" data-cites="jones1995rd">Charles I. Jones (<a href="#ref-jones1995rd" role="doc-biblioref">1995</a>)</span> introduced diminishing returns to knowledge, whereas Romer (1990) had assumed no diminishing returns to knowledge, <span class="math inline">\(\beta=0\)</span>.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("tecunningham\.github\.io");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>