---
title: On Deriving Things
author: Tom Cunningham
date: today
fontsize: 15pt
draft: true
---

<!-- nothing true is surprising, just you have the wrong analogies, it's all true -->

<!-- all mistakes are equivocation -->

<!-- Going to sleep I cracked something , take the integral vertically instead of horizontally ; for a few months I would save some juicy problem to contemplate as I drifted off ; -->

1. **I've spent a lot of time trying to prove things,** with diagrams and algebra, back and forth between clipboard whiteboard blackboard & keyboard.

2. **I can't talk about what this experience is like for a good mathematician but I can talk about it for a hack:** I can prove true & interesting things occasionally but only after wallowing in it for a long time, and having believed that I've proved a half-dozen things true that, later, I realize are false.

3. **For each conclusion I find a few different sets of assumptions that are sufficient, and for each set of assumptions I can find a few different conclusions that are implied.** I don't want to write out every permutation, I want to find the weakest assumptions that implies the strongest conclusion. Finding the right choice requires being satured in the whole problem: I can't just spend an hour a day, I need to collect all the pieces into my brain to be aware of the beginning, the middle, the end.

4. **Then eventually the relief of finding the hidden door:** suddenly I see the inequalities as holding down variables like saxophone keys, which gives me the lemma: a condition for a set of inequalities between the elements of two vectors to imply an inequality between the sums of the vectors. I don't need to write it down, I can take a break and make a sandwich, it's enough to remember saxophone keys. Later I find out this is called Hall's marriage theorem.

5. **Perhaps 1/3 of my time is actually concentrating on the problem.** If it's programming or writing I can just bring up a window and type away. If it's deriving things then my mind is constantly drifting, trying to find some other path to go down -- in reverie, doodling Zeus, refilling my pen, looking something up.

6. **Working my way towards my conclusions I have to pass obstacles** -- a canyon, a dragon, a moat. When it's going well it's a thrill, I defeat them one by one, I'm on a roll and I don't want to get up to have lunch.

7. **I'll be writing out an equation for the 3rd time hoping my brain will recognize something,** and instead a dusty image will be released:  a sparse park in Manchester, a man who blanked me in a corridor in London, a cheese shop in Stockholm.

   Quietening the brain to concentrate on just one thing and the background noise becomes audible. I hear the mice scratching in the walls. Not just the familiar memories, unfamiliar long-lost memories come out too.

8. **Sometimes the goal is to maximize the distance between the assumptions and the conclusion,** to make it seem more impressive. At first the starting point and end point are within sight of each other, and I hack away at either side, loosening the assumptions, tightening the conclusions, until the path stretches as far as possible.

      A real danger is that I end up chasing what *looks* impressive. I twist the wording of the assumptions to make them seem weaker than they are, the conclusions to seem stronger, or hide ancillary assumptions in the body of the derivation. Looking back to some of my old papers I see signs of this and I'm ashamed of it.

9.  **Often I'll over-estimate what I can accomplish:** I'll have some cocky confidence that, this time, I can prove something I've failed to prove before. Or I'll have a sketch and decide that it's good-enough, that I can fill in the details later. Then later get a sickening feeling discovering that it's really nothing, the bits omitted from the sketch were exactly the difficult parts. The voice in my head that causes these over-optimistic judgments causes other griefs in my life I think.


9. **When notes are scattered all over the desk the question is whether to write up what I have or push on towards the summit.** It's a dangerous tradeoff. In retrospect it seems like I've often made the wrong decision: too-often tried for the summit, failed, and then left without good notes about what I tried. I come back to make another attempt and see my old footsteps and regret that I didn't spend more time hammering nails into the rock.

10. **There are a half-dozen different things I need to intentionally keep ambiguous because I're not sure which disambiguation will resolve it.** Whether to use strict or weak preferences; whether the numbering should start at zero or one; whether naturals or wholes or integers. Making a decision at one stage has implications for others. This part is Sudoku, finding something which fits many constraints.

11. **Sometimes a gap seems to open up between what's important and what's orthodox.** If I make an assumption that is somewhat stronger than typical then everything is much more elegant and, it seems, I can keep focus on what's important. But then I get memories of being in seminar rooms and seeing the speaker making an unorthodox assumption and how the energy drains out of the room.

12. **I take a problem and present it to my intuition to see if it recognizes something.** I show it from different angles: vary the notation, write worked examples, draw arrow diagrams, draw venn diagrams, hoping that one of these approaches will trigger a memory of seeing this type of thing before.

13. **I walk around the house checking the windows and doors.** I check whether the answers are in the right units: dollars/person, quantity/year, and I check whether the signs go in the right direction.

14. **Beer at the dreary Birkbeck bar:** we were all around 30 but still grasping around for things to say to each other to fill up an evening with. When we heard the kids roaring by the pool table we all looked up.

15. **I lose track of which way the inequality should be pointing, $>$ or $<$.** My intuition doesn't give me a strong signal so I just choose one and stick with it hoping that once I arrive at the conclusion I can work backwards and fix the directions.

      Margaret Bray at the LSE told me that when she worked as a research assistant to Joseph Stiglitz in the 1970s she would find errors in his proofs, and when she found an odd number of sign errors, instead of an even number, she would tell him about it and he'd quickly rewrite the discussion of that result: substituting an intuitive explanation of why the effect of $\theta$ on F was negative for what had been an explanation of why the effect of $\theta$ on F was positive.

16. **On a good day it's like swimming in cold water:** I don't want to get in but once I'm in I don't want to get out. Once my chair is firmly pushed in at the desk I don't want to get up to get a snack, to check the mail, I don't want to go to the bathroom, I'll be working through proofs while shaking my legs trying to stretch my bladder out.

      I'm a bit unwilling to start working on a revision but I know that once I'm back in the middle of it I'll see flaws in it and want to fix them, and it's difficult to stop working on it.

17. **On a bad day I'm rotating slices of a Rubik's cube at random, checking to see if it's solved, then rotating again.**

18. **Flashing recollection of other peoples' seminars and papers:** they seemed so boring at the time and now my paper seems so similar to theirs.

19. **The ideal state of mind has both things:** (1) the clarity of fresh eyes; and (2) the suppleness of familiarity. For that reason it makes sense to work long days.

20. **The feeling that a proof is in sight is distinct from other pleasures.** It's final and discrete. Every decision in my life could turn out to have been a mistake in retrospect. A proof is different. Very likely everything I've proved has been proved earlier and better but that doesn't do much to detract.

21. **Making Will's grandmother a shandy of beer and lemonade** Noticing the shadows of the roses in her garden, how they would change when I stood near them, the proximity of my shadow would somehow make the shadows of the roses come into focus.

22. Writing $\bar{k}$ reminds me of k-bars (hard candy in NZ), and the bar-kays (Stax records soul group).

23. **Weaselly unworthy thoughts that bubble up:** that a reader will be impressed by the quantity and complexity of the proof, and give me credit for that.

24. **When I'm trying to concentrate hard on something difficult, & still my mind, my weasel thinks of something I should order on Amazon.** I can suppress that. My weasel tries to get me to look up how to do a LaTeX symbol that would be useful (delta-over-equals). I can suppress that. Weasel sees a pair of brackets that could have an extra space: I give in and go fix the brackets. But once I've given in it becomes easy to follow the Weasel on to other naughty things. And then after a while the Weasel tells me that it's almost lunchtime: I look back on my 3-hour block of time and it looks like swiss cheese.

25. **I'm a grown adult but my concentration is still not under my control.** I put out treats for it, entreating it like a dog. Teach it bad habits. Give in to its whims.

26. **Sometimes I'm stumbling through equations trying to derive one from another but I have lost track of what they mean.** Like going through a room in the dark grasping for a door handle. I want to go back and draw some diagrams to get an intuition of what's going on, some mental picture, but sometimes I try and try and nothing comes. So I go back to the proof.

27. **Getting in the zone.** Achieving flow. When I switched from programming to studying economics I missed those numb hours that would pass by. I noticed that some people get it when they're deriving things but it's difficult for me to achieve that.

      When you're programming you get incremental feedback: you know you're making some concrete progress, you can see the mountain peak and you're slowly getting closer to it. With proofs you're going through the jungle and you don't know if you're getting closer or farther away. You could suddenly emerge into a clearing or you might be in this forest for months.

28. **A Miami hotel parking lot at dusk.**

29. **I read through the paper and I change a semicolon to a comma;** I read it again and remove the comma; I read it again and add a semicolon.

30. **Why am I doing this?** As I'm feeling around a problem I think of a guy I knew from seminars in Cambridge who would pause when a new slide came up and then nod quietly. Am I doing this for intrinsic or extrinsic reasons? 

31. **When I'm working I have a vision of the grand structure I'm going to build,** I don't mind making a mess while I'm working. I have a confidence that each of these things will coalesce. The confidence an entrepreneur projects their employees up to the day that the bailiffs arrive.

32. **I took a month off work to prove some results.** The first week I kept regular hours, I worked on pieces in a logical order, I didn't check my phone. By the third week I was sitting on the bed at 10 in the morning eating corn chips scrolling through Twitter. Taking a day off helps, the energy returns the following day. It's strange that it's so predictable.

33. **In Tel Aviv I would swim in the sea.** By the third week I was still going down to the beach, getting in the water, and starting to swim, but after 30 seconds I would let my legs fall to the sand and just walk through the water for a bit, staring into space and thinking. Then I would remember to start swimming again.

34. **Success gets success.** My imagination of a referee reading the paper: "jesus what is this? what a mess." That thought sucks the strength out of me and makes me vulnerable to distracting thoughts; also makes me more vulnerable to grandiose voices -- trying to impress the referee.

35. **I switch between two modes: what is true? how do I prove it?** They are very different. In the second mode it's just trying to keep everything straight to nail it down but then occasionally a sickening feeling that it's not my clumsiness that's holding me back but perhaps the thing isn't true after all, and I have to return to the first mode.

36. **Reading through an old draft like a landlord returning to his estate after a long trip,** reminded of the state of things. I'm more often surprised unpleasantly than pleasantly. My memory must be pickling things in a sweet vinegar.

37. **Coming back to writing a paper after 5 years at Facebook I had a very different kind of confidence.** Old anxieties are about not doing things in the right way. Now I feel that if it makes sense to me I won't be embarrassed by it. I might be wrong but I'm not a fraud. This releases a great deal of otherwise pent-up energy.

38. **Saturday morning on the way back from the vegetable market in Farringdon.** I sit down with a sandwich in a churchyard and I see my German neighbors are there too. I'm self-conscious that my loneliness is exposed.

39. **Representation of a problem getting gradually more abstract:** a matrix; a scrawl; using the same symbol to denote 3 different things; marks to denote an abstraction upon an abstraction; a jenga tower almost to the ceiling. I'm holding it very delicately and it's crucial not to lose that concentration as I can see it teeter. Sometimes I stare out the window too long and when I look back down at the page the symbols no longer make sense: was this a matrix and that a vector? Why was I multiplying them together in this weird way? Ah shit.

40. **Always comparing myself, and necessarily.** Am I smarter than I was last month? My decision about whether to attempt solving this problem depends on that judgment. I see that the problem I'm attempting is one that was notably not solved in a paper by Benabou and Tirole: whether I should give up now depends on how I assess my ability compared to theirs. I've spent two hours trying out different matrices to see if they have a certain property, looking for a generalization about which matricies satisfy it, I still haven't got one and now I don't recall why I felt this was important -- how much do I trust my decision to go down this road, and at what point do I go back to reconsider whether this problem is worth solving?

41. **I see my coauthor changing an assumption in the setup of our paper.** Taking apart a Lego car to rearrange the unsatisfactory front wheels but it's hard to anticipate all the downstream consequences of that; I don't remember all the considerations I had in mind when I put together the front wheels.  <!-- Rotating a slice of Rubik's cube in to complete the yellow face while only half paying attention to the state of the other 5 faces. -->



# Anatomy of a Mistake

**I missed a malignant ambiguity because there was *another* ambiguity next to it, and that other ambiguity was benign.**

There were two versions of a claim:

$$\theta(x,x') = \theta(x'-x)\tag{A weak}$$

$$\theta(x,x') = \theta(|x'-x|)\tag{A strong}$$


<!-- $$\begin{aligned}
      \theta(x,x') &= \theta(x'-x)     && \text{(weak version)} \tag{1}\\
      \theta(x,x') &= \theta(|x'-x|)   && \text{(strong version)} \tag{2}
\end{aligned}$$ -->

My conclusion required the strong version but my assumptions only justified the weak version.

Why did I miss this? Because there was *another* ambiguity that was floating around. Call the thing above claim 1, and there's also claim 2:

   $$\theta_i(x,x') - \theta_i(x+1,x') > 0. \tag{B}$$
   
It happens that assuming $\mu=0$ implies both (B) and (A-strong). My thought process:

- I don't want to restrict to $\mu=0$.

- I knew that claim-2 is not true for all $\mu$, but I knew that it's true for sufficiently small values, i.e. $|\mu|<k$ for some $k$.

- So I had two versions of an assumption ($\mu$ is zero, $\mu$ is small), and two versions of (A).

- When my mind wandered onto whether claim (A strong) was justified I was reassured by remembering that it'll work when $\mu=0$ (true for both claim 1 and 2), and additionally that for $\mu=\epsilon$ it'll be OK (true only of claim 2).

The key thing: if claim 2 had not have interfered I wouldn't have made this mistake.

Like a pickpocket will wait for you to move before pulling out your wallet, because the friction you feel on your buttock could be from the walking.


#                          Some things I proved

1. **How to interpret experiments with two outcomes:** your posterior depends on priors about correlations between treatment-effects, and correlations in noise.

2. **When trade-off curves look like ellipses.** If you're ranking items by predictions, e.g. ranking by $p(A)+\beta p(B)$, and the predictions are calibrated, with Gaussian distributions, then the overall tradeoff between $A$ and $B$ will be an ellipse, equal to an isovalue of the joint distribution of $F(p(A),p(B))$.

3. **If information is stored in separate systems in the brain this will cause characteristic inconsistencies in decision-making.**


<!-- 

20. **Some problems feel intractable:** I keep butting my head & it doesn't feel like I can get a grip. (The problem of solving the sophisticated-signalling model: need to find a sufficient condition such that a complicated inequality will be true, and it's just hard.)



--------------------------------------------

38. **The sickening feeling that it won't come together.** Like the feeling that your life is a lie: it's all deception and it's going to start falling apart. I was adopted, my girlfriend has been cheating on me, my colleagues laugh at me.


# Memories


North End Park by the cricket cages, hanging around on the edges of some big school activity.

#### 

Winchelsea graveyard at dawn.

#### 

Red-head kid giving us browneye at moana pool.

#### 

Top floor toy section of Arthur Barnetts: big open room, attendant in center surrounded by a counter, train set. Staircase and an elevator with solid cylindrical buttons.



#                 Offcuts


When people are stuck in prolonged debates, they can't see the mistake they're making, often because there are two versions of the mistakes: shallow and deep. Whenever they introspect on their reasoning they only see the shallow mistake, and that prevents them from seeing the deep one.

#### Leaping across.

Need to get across, leave a gap, come back to it later.

#### When you thought you proved something.

// (Sickening feeling)

#### Intelligence vs focus.

#### Key variable: how many things you can hold in your head.

// If you can hold a lot of things in your head at once, good time to work on core problems. If few, work on the periphery.

#### Progressively higher layers of abstraction.

#### Metaphors.

\(1\) putting together ikea furniture without the manual -- lots of permutations, need to keep them all in mind;

#### Failures come from equivocation.

(\...)

#### self-consciousness eating up a piece of work.

-   Eating it from the inside like rust on a car. // Seeing people write papers, write analyses, there are really clear questions which they don't ask themselves.

-   (it's natural to be benchmarking your own abilities against other people -- )

-   (corrosive: (1) recommending multiple corrections; (2) )

-   Trap: choosing your words carefully, you don't want to .


#### 

Some extraordinary pedantry: spending paragraphs defining things that are perfectly clear from the context. When I see a lecturer do that I get impatient. There's an implication that if you don't wear your seatbelt you'll regret it, but I'm doubtful, a conviction that we could prove so much more if we didn't spend time on these superficialities.

#### 

(see note in prussia-log-2021 2021-03-14)

#### 

(still don't quite have the courage to be perfectly frank.)

#### 

Hierarchy of work: spend a day trying to derive something and finish
with nothing. write about some problem, definitely will have something,
but hard to predict; do programming, fine.

#### 

Feeling that this must be true (saxophone lemma) yet I don't know how to
prove it. Implicit knowledge.

#### Smoothing out a tablecloth with one hand.

If I only give half my attention to something then I'll make no progress
at all and it'll be attention wasted.



#### Fundamental problem.

Find a permutation that satisfies multiple constraints. It's not a convex problem, you can't follow the path of satisfying each constraint one by one. Instead it's like a rubik's cube or sudoku. If you map out the landscape it will look very spiky: the mountain you're trying to find is surrounded by valleys.


If the solution is complicated then it's probably my mistake. , then I think most-likely I did something wrong. God doesn't play dice.


   [A similar story about Hilbert:](https://www.ams.org/notices/199701/comm-rota.pdf)

   > "When the Germans were planning to publish Hilbert's collected papers and to present him with a set on the occasion of one of his later birthdays, they realized that they could not publish the papers in their original versions because they were full of errors, some of them quite serious. Thereupon they hired a young unemployed mathematician, Olga Taussky-Todd, to go over Hilbert's papers and correct all the mistakes. Olga labored for three years; it turned out that all the mistakes could be corrected without any major changes in the statement of the theorems. There was one exception: a paper Hilbert wrote in his old age which could not be fixed. It was a purported proof of the continuum hypothesis; you will find it in a volume of the Mathematische Annalen of the early thirties. At last, on Hilbert's birthday a freshly printed set of Hilbert's collected papers was presented to the Geheimrat. Hilbert leafed through them carefully and did not notice anything." --

1. Solving a difficult problem is like disassembling a complicated piece of machinery to try to fix it. The success is all-or-nothing. You can't put in a little bit of time every day, you have to set aside some long blocks of time to concentrate wholly on this. (Figure with an exploded of an engine.)


10. **I'm 14, in the kitchen of my best-friend's grandmother, making her a shandy of beer and lemonade.** 



1. **Moving from one line of the proof to the next I'll be surprised to come across a memory from years ago:** a sparse park in Manchester, a man who blanked me in a corridor in London, a cheese shop in Stockholm.

**Explaining things to someone else.** When a problem becomes tough the answer often falls out half-way through the process of writing up the problem to explain to a friend.

-->