---
title: If You Overtake More Runners than You're Overtaken by
author: Tom Cunningham
date: 2026-03-07
draft: true
execute:
  echo: false
  cache: true # caches chunk output
fig-align: center
reference-location: margin
format:
   html:
      toc: true
      toc-depth: 2
      toc-location: left
      code-fold: true
      html-math-method:
         method: mathjax
         url: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg-full.js"
         #     ^ this forces SVG instead of CHTML, otherwise xypic renders weird
      include-in-header:
         - text: |
            <script>window.MathJax = {
                     loader: { load: ['[custom]/xypic.js'],
                                 paths: {custom: 'https://cdn.jsdelivr.net/gh/sonoisa/XyJax-v3@3.0.1/build/'}},
                  tex: {packages: {'[+]': ['xypic']},
                     macros: {
                        bm: ["\\boldsymbol{#1}", 1],
                        ut: ["\\underbrace{#1}_{\\text{#2}}", 2],
                        utt: ["\\underbrace{#1}_{\\substack{\\text{#2}\\\\\\text{#3}}}", 3]
                     }}};
            </script>
engine: knitr
# editor:
#    render-on-save: true
---
<style>
   h1 {  border-bottom: 4px solid black;}
   h2 {  border-bottom: 1px solid gray; padding-bottom: 0px; font-size: 14px; color: black; }
   dl {display: grid;grid-template-columns: max-content auto;}
   dt {grid-column-start: 1;}
   dd {grid-column-start: 2; margin-left: 2em;}
</style>

<!-- https://tecunningham.github.io/posts/2023-08-13-runner-percentile.html -->

**Suppose you overtake 10 times as many runners as overtake you. What can you say about your speed relative to the other runners?** For concreteness, suppose everyone is running around a circular track in the same direction forever, and each person started at a random point.

**Answer:** We can write the general relationship as follows:
   $$\frac{\text{frequency of passing}}{\text{frequency of being passed}}
         =\frac{\text{share slower runners}}{\text{share faster runners}}
            \times
            \frac{\text{avg excess above slower runners}}{\text{avg lag behind faster runners}}
            %= \frac{E[s-x|x<s]}{E[x-s|x>s]}\frac{P(x<s)}{P(x>s)}
   $$

   **The ratio of slower/faster will not generally be equal to the ratio of passing/passed.** The reason is that your propensity to encounter another runner depends on the difference in speeds: you will rarely pass or be passed by those who run similar speeds to you.

   **Some additional implications:**

   1. If you're passing the same number of people as pass you, then you must be running exactly the mean speed.
   2. If the distribution of running speeds is Gaussian, then your ratio of passing/passed exaggerates your position in the distribution of speeds, e.g. if you pass 10x as many people as pass you then there are *fewer* than 10x as many people who are slower than you relative to people who are faster than you.
   3. If the distribution of running speeds is symmetric and log-concave, then exaggeration holds whenever you're above the center of the distribution. This covers the Normal, logistic, Laplace, and uniform distributions.
   4. If the distribution of running speeds is sufficiently fat-tailed (e.g. a $t$-distribution with $\mathrm{df}<2$), then you can get the opposite implication.
   5. (due to Matt Parry) If mean and variance exist, then your pass/passed ratio also gives an upper bound on how many standard deviations above the mean you can be:
      $$s-\mu \le \frac{r-1}{2\sqrt{r}}\sigma$$
      where $r$ is your ratio of pass/passed.

([original FB post](https://www.facebook.com/tom.cunningham.374549/posts/pfbid0enA2CUnsfnukfqAwKPmvjDig33bqzs1J1X43KVMrZKRVDK2d5p2Q83dEhC7TPj4Sl))


#           Derivation

   $$\begin{aligned}
      s &= \text{my speed} \\
      x &\sim \phi, \text{other runners' speeds} \\
      p=\text{runners I pass}
         &= \int_{-\infty}^s \utt{\phi(x)}{runners}{at speed $x$}\utt{(s-x)}{frequency}{we pass}dx\\
         &= s\Phi(s)-\int_{-\infty}^sx\phi(x)dx \\
      q= \text{runners who pass me}
         &= \int_{s}^\infty \utt{\phi(x)}{runners}{at speed $x$}\utt{(x-s)}{frequency}{we pass}dx\\
         &= \int_{s}^{\infty}x\phi(x)dx-s(1-\Phi(s)) \\
      r=\text{ratio pass/passed}
         &= \frac{s\Phi(s)-\int_{-\infty}^sx\phi(x)dx}
            {\int_{s}^{\infty}x\phi(x)dx-s(1-\Phi(s))} \\
         &= \utt{\frac{E[s-x|x<s]}{E[x-s|x>s]}}{ratio of avg excess above slower}{to avg lag behind faster}
            \utt{\frac{P(x<s)}{P(x>s)}}{ratio of slower}{to faster}
   \end{aligned}
   $$

This last expression is the most important. It implies you can figure out your rank among runners $\frac{P(x<s)}{P(x>s)}$ if you know the relative distance in speeds among those who are faster and those who are slower. If the speed differences are identical then the two ratios are the same. For the Normal distribution, the conditional expectations are such that the slower runners are closer than the faster runners, implying the exaggeration property.

Derivation of the final condition:
   $$\begin{aligned}
      E[x|x<s]
         &= \frac{\int_{-\infty}^s x\phi(x)dx}{\Phi(s)}\\
         &= s-\frac{p}{\Phi(s)}
         && \text{(from above)} \\
      E[x|x>s]
         &= \frac{\int_{s}^{\infty} x\phi(x)dx}{1-\Phi(s)}\\
         &= s+\frac{q}{(1-\Phi(s))}\\
      \frac{E[x|x<s]-s}{E[x|x>s]-s}
         &= -\frac{p}{q}\frac{1-\Phi(s)}{\Phi(s)}\\
      r=\frac{p}{q}
         &= \frac{E[s-x|x<s]P(x<s)}{E[x-s|x>s]P(x>s)}
   \end{aligned}
   $$

One sufficient condition for exaggeration:
   let
   $$\begin{aligned}
      U_s &= s-x \mid x<s \\
      V_s &= x-s \mid x>s
   \end{aligned}
   $$

Then
   $$\begin{aligned}
      E[U_s] &= E[s-x|x<s] \\
      E[V_s] &= E[x-s|x>s]
   \end{aligned}
   $$

so exaggeration holds if $U_s$ stochastically dominates $V_s$. Their survival functions are
   $$\begin{aligned}
      P(U_s>t)
         &= \frac{F(s-t)}{F(s)} \\
      P(V_s>t)
         &= \frac{1-F(s+t)}{1-F(s)}
   \end{aligned}
   $$

Now suppose the density is symmetric about $c$ and log-concave. Then $F$ is log-concave, so for each fixed $t\ge 0$ the function
   $$g_t(x)=\log F(x-t)-\log F(x)$$

is increasing in $x$. By symmetry,
   $$\frac{1-F(s+t)}{1-F(s)}=\frac{F(2c-s-t)}{F(2c-s)}$$

and if $s\ge c$ then $2c-s\le s$, so
   $$\frac{F(s-t)}{F(s)}\ge \frac{F(2c-s-t)}{F(2c-s)}=\frac{1-F(s+t)}{1-F(s)}$$

for all $t\ge 0$. Therefore $U_s$ stochastically dominates $V_s$, so
   $$E[s-x|x<s]\ge E[x-s|x>s]$$

and exaggeration follows.

Bound in standard deviations (assuming mean and variance exist):
   $$\begin{aligned}
      \mu &= E[x] \\
      \sigma^2 &= \mathrm{Var}(x) \\
      a &= E[(s-x)_+] \\
      b &= E[(x-s)_+] \\
      r &= \frac{a}{b} \\
      s-\mu
         &= E[s-x] \\
         &= a-b \\
         &= (r-1)b \\
      E|s-x|
         &= a+b \\
         &= (r+1)b \\
         &= \frac{r+1}{r-1}(s-\mu) \\
      E|s-x|
         &\le \sqrt{E[(s-x)^2]} \\
         &= \sqrt{(s-\mu)^2+\sigma^2}
   \end{aligned}
   $$

So
   $$\begin{aligned}
      \frac{r+1}{r-1}(s-\mu)
         &\le \sqrt{(s-\mu)^2+\sigma^2} \\
      \left(\frac{r+1}{r-1}\right)^2(s-\mu)^2
         &\le (s-\mu)^2+\sigma^2 \\
      \frac{4r}{(r-1)^2}(s-\mu)^2
         &\le \sigma^2 \\
      s-\mu
         &\le \frac{r-1}{2\sqrt{r}}\sigma
   \end{aligned}
   $$

#           Uniform Distribution of Speeds

With a uniform distribution you can easily see that the number of passing events is proportional to the area of the triangle, and so proportional to the *square* of the number of runners below/above your speed.

```{tikz}
\begin{tikzpicture}
   \draw[<->] (-2,2)-- node[above,rotate=90]{runners} (-2,0)-- (2,0) node[right]{speed};
   \fill[gray] (-1.5,0) -- (-1.5,1) -- (1.5,1) -- (1.5,0) -- cycle;

   \draw[dashed] (1,-5) node[below]{$p$} -- (1,2) node[right,rotate=90]{my speed};
   \node[right] at (1.6,1) {distribution of other runners};

   \draw[<->] (-2,-.5) -- (-2,-2);
   \draw[->] (-2,-1.25) -- (2,-1.25) node[right]{};
   \draw[line width=1] (-2,-2) -- (2,-1) node[right,align=center]{frequency of passing each other};

   \draw[<->] (-2,-2.5) -- (-2,-4);
   \draw[->] (-2,-3.25) -- (2,-3.25) node[right]{};
   \fill[blue] (-1.5,-3.67) -- (1,-3.25) -- node[midway,above,black] {I pass} (-1.5,-3.25) -- cycle;
   \fill[pink] (1,-3.25) -- (1.5,-3.13) -- node[above,black,align=center] {pass\\me} (1.5,-3.25) -- cycle;

\end{tikzpicture}
```

#           Normal Distribution of Speeds

```{tikz}
#| column: margin
\pgfmathdeclarefunction{gauss}{3}{\pgfmathparse{1/(#3*sqrt(2*pi))*exp(-((#1-#2)^2)/(2*#3^2))}}
\tikzset{declare function={normcdf(\x,\m,\s)=1/(1 + exp(-0.07056*((\x-\m)/\s)^3 - 1.5976*(\x-\m)/\s));}}
\begin{tikzpicture}
   \draw[<->] (-2,2)-- node[above,rotate=90]{num runners} (-2,0)-- node[below] {speed}(2,0);
   \draw[domain=-2:2] plot({\x},{3*gauss(\x,0,1)});
   %\draw[domain=-2:2] plot({\x},{2*normcdf(\x,0,1))}) node[right]{$F(c)$};
   \draw[dashed] (1,0) node[below]{$s$} -- (1,2) node[right,rotate=90]{my speed};
   \node[align=center] at (0,1.5) {Density of runners\\$\phi(x)$};
\end{tikzpicture}
```

```{tikz}
#| column: margin
\pgfmathdeclarefunction{gauss}{3}{\pgfmathparse{1/(#3*sqrt(2*pi))*exp(-((#1-#2)^2)/(2*#3^2))}}
\tikzset{declare function={normcdf(\x,\m,\s)=1/(1 + exp(-0.07056*((\x-\m)/\s)^3 - 1.5976*(\x-\m)/\s));}}
\begin{tikzpicture}
   \draw[<->] (-2,2)-- (-2,0)-- (2,0);
   \fill[gray,domain=-2:2] (-2,0) -- plot({\x},{(\x-1)*gauss(\x,0,1)}) -- (2,0);
   %\draw[domain=-2:2] plot({\x},{2*normcdf(\x,0,1))}) node[right]{$F(c)$};
   \draw[dashed] (1,0) -- (1,2);
   \node[align=center] at (0,1) {Relative passing rate\\$\phi(x)(s-x)$};
   \node[align=center] at (-.5,-.8) {I pass them};
   \node[align=center] at (1.5,-.5) {they\\pass\\me};
\end{tikzpicture}
```

```{tikz}
#| column: margin
\pgfmathdeclarefunction{gauss}{3}{\pgfmathparse{1/(#3*sqrt(2*pi))*exp(-((#1-#2)^2)/(2*#3^2))}}
\tikzset{declare function={normcdf(\x,\m,\s)=1/(1 + exp(-0.07056*((\x-\m)/\s)^3 - 1.5976*(\x-\m)/\s));}}
\begin{tikzpicture}
   \draw[<->] (-2,2) -- (-2,0) node[rotate=90,midway,above,align=center]{people I pass\\per minute}-- (2,0) node[midway,below] {my speed};
   \draw[domain=-2:2] (-2,0) -- plot({\x},{gauss(\x,0,1)+\x*normcdf(\x,0,1)}) -- (2,0);
   \draw[domain=-2:2,red] (-2,0) -- plot({\x},{2*gauss(\x,0,1)}) -- (2,0) node[right]{$2\phi(s)$};
   \draw[domain=-2:2,blue] (-2,0) -- plot({\x},{\x*normcdf(\x,0,1)}) node[right]{$s\Phi(s)$};
   \draw[dashed] (0,0)--(0,1);
   \node at (0,2) {$\phi(s)+s\Phi(s)$};
\end{tikzpicture}
```

```{tikz}
#| column: margin
\pgfmathdeclarefunction{gauss}{3}{\pgfmathparse{1/(#3*sqrt(2*pi))*exp(-((#1-#2)^2)/(2*#3^2))}}
\tikzset{declare function={normcdf(\x,\m,\s)=1/(1 + exp(-0.07056*((\x-\m)/\s)^3 - 1.5976*(\x-\m)/\s));}}
\begin{tikzpicture}
   \draw[<->] (-2,2) -- (-2,0) node[rotate=90,midway,above,align=center]{people who pass me\\per minute}-- (2,0) node[midway,below] {my speed};
   \draw[domain=-2:2] (-2,0) -- plot({\x},{gauss(\x,0,1)-\x+\x*normcdf(\x,0,1)}) -- (2,0);
   \draw[dashed] (0,0)--(0,1);
   \node at (0,2) {$\phi(s)-s(1-\Phi(s))$};
\end{tikzpicture}
```

<!-- ```{tikz}
#| column: margin
\pgfmathdeclarefunction{gauss}{3}{\pgfmathparse{1/(#3*sqrt(2*pi))*exp(-((#1-#2)^2)/(2*#3^2))}}
\tikzset{declare function={normcdf(\x,\m,\s)=1/(1 + exp(-0.07056*((\x-\m)/\s)^3 - 1.5976*(\x-\m)/\s));}}
\begin{tikzpicture}
   \draw[<->] (-2,2) -- (-2,0) node[rotate=90,midway,above,align=center]{ratio}-- (2,0) node[midway,below] {my speed};
   \draw[domain=-2:2] (-2,0) -- plot({\x},{(gauss(\x,0,1)+\x*normcdf(\x,0,1))/(2*gauss(\x,0,1)+\x*normcdf(\x,0,1)-\x)}) -- (2,0);
   \draw[domain=-2:2,red] (-2,0) -- plot({\x},{(normcdf(\x,0,1))/(1-normcdf(\x,0,1))}) -- (2,0);
   \draw[dashed] (0,0)--(0,1);
   \node at (0,2) {ratio};
\end{tikzpicture}
``` -->

```{tikz}
\pgfmathdeclarefunction{gauss}{3}{\pgfmathparse{1/(#3*sqrt(2*pi))*exp(-((#1-#2)^2)/(2*#3^2))}}
\tikzset{declare function={normcdf(\x,\m,\s)=1/(1 + exp(-0.07056*((\x-\m)/\s)^3 - 1.5976*(\x-\m)/\s));}}
\begin{tikzpicture}
   \draw[<->] (-2,1) -- (-2,0) node[rotate=90,midway,above]{share I pass}-- (2,0) node[midway,below] {my speed};
   \draw[domain=-2:2] (-2,0) -- plot({\x},{(\x*normcdf(\x,0,1)+gauss(\x,0,1))/(2*\x*normcdf(\x,0,1)+2*gauss(\x,0,1)-\x)}) -- (2,0);
   \draw[domain=-2:2,red] (-2,0) -- plot({\x},{normcdf(\x,0,1)}) -- (2,0);
   \draw[dashed] (0,0)--(0,1);
   \node at (0,1.5) {$\frac{s \Phi(s) + \phi(s)}{2s\Phi(s) + 2\phi(s) - s}$};
   \node[rotate=90,below,red,align=center] at (2,.5) {percentile\\of runners};
\end{tikzpicture}
```

$$\begin{aligned}
   s &= \text{my speed} \\
   x &\sim \phi, \text{other runners' speeds} \\
   \text{runners I pass}
      &= \int_{-\infty}^s \utt{\phi(x)}{runners with}{speed $x$}\utt{(s-x)}{rate I}{pass them}dx\\
      &= s\Phi(s) - \int_{-\infty}^s x\phi(x) dx \\
      &= s \Phi(s) + \phi(s) \\
      & \text{(last step uses $\phi=N(0,1)$)}\\
   \text{runners who pass me}
      &= \int_{s}^\infty \utt{\phi(x)}{runners with}{speed $x$}\utt{(x-s)}{rate they}{pass me}dx\\
      &= \left[  -\phi(x) -s\Phi(x)  \right]^\infty_s \\
      &= (0+\phi(s)) - (s-s\Phi(s))\\
      &= \phi(s) - s + s\Phi(s) \\
   r=\text{ratio pass/passed by}
      &= \frac{s\Phi(s)+\phi(s)}{\phi(s)+s\Phi(s)-s}\\
   \text{share I pass}
      &= \frac{s \Phi(s) + \phi(s)}{s \Phi(s) + \phi(s)+\phi(s) - s + s\Phi(s)} \\
      &= \frac{s \Phi(s) + \phi(s)}{2s\Phi(s) + 2\phi(s) - s}
\end{aligned}
$$

**Note on derivatives:**


$$\begin{aligned}
   \phi(x) &= \frac{1}{\sqrt{2\pi}}e^{-x^2/2}
      && \text{(standard normal)}\\
   \phi'(x) &= -x\phi(x)
\end{aligned}
$$

#           Simulations

Each cell in the table below shows first the ratio pass/passed, then the ratio slower/faster, for a given speed $s$. We can see that exaggeration holds in the Gaussian and $t(\mathrm{df}=2)$ examples, but not in the $t(\mathrm{df}=1)$ example.

Note that $t$ with $\mathrm{df}=1$ is weird because it doesn't have an expectation, i.e. $x\phi(x)$ never goes to zero, so it is harder to think about.

```{r}
format_stat <- function(x) {
    if (is.nan(x)) {
        return("NaN")
    }
    if (is.infinite(x)) {
        return("Inf")
    }
    if (abs(x) >= 1e4) {
        return(formatC(x, format = "e", digits = 2))
    }
    if (abs(x) >= 100) {
        return(sprintf("%.0f", x))
    }
    if (abs(x) >= 10) {
        return(sprintf("%.1f", x))
    }
    return(sprintf("%.2g", x))
}

pass <- function(x) {
    x * pnorm(x) + dnorm(x)
}
passed <- function(x) {
    x * pnorm(x) + dnorm(x) - x
}
share <- function(x) {
    pass(x) / (pass(x) + passed(x))
}
ratio <- function(x) {
    pass(x) / passed(x)
}

ratio_sum <- function(x, density) {
    range <- 100
    percentile <- 0
    for (speed in seq(-range, x, 0.1)) {
        percentile <- percentile + density(speed) * 0.1
    }
    pass <- 0 # people you pass
    for (speed in seq(-range, x, 0.1)) {
        pass <- pass + density(speed) * (x - speed) * 0.1
    }
    passed <- 0 # people you're passed by
    for (speed in seq(x, range, 0.1)) {
        passed <- passed + density(speed) * (speed - x) * 0.1
    }
    # return (pass/passed) and (slower/faster)
    return(c(pass / passed, (percentile / (1 - percentile))))
}

format_pair <- function(values) {
    paste(format_stat(values[[1]]), format_stat(values[[2]]), sep = " / ")
}

s_values <- c(-1, 0, 0.5, 1, 2, 10)

table_df <- data.frame(
    s = s_values,
    gauss = vapply(
        s_values,
        function(s) format_pair(c(ratio_sum(s, dnorm))),
        character(1)
    ),
    `t(df=1)` = vapply(
        s_values,
        function(s) format_pair(c(ratio_sum(s, function(x) dt(x, df = 1)))),
        character(1)
    ),
    `t(df=2)` = vapply(
        s_values,
        function(s) format_pair(c(ratio_sum(s, function(x) dt(x, df = 2)))),
        character(1)
    ),
    check.names = FALSE
)

knitr::kable(table_df, col.names = c("speed ($s$)", "N(0,1)", "t(df=1)", "t(df=2)"))
```


#           References

**Mathoverflow (2010) ["You pass X people and Y people pass you: how relatively fast are you?"](https://mathoverflow.net/questions/40913/you-pass-x-people-and-y-people-pass-you-how-relatively-fast-are-you)**
   
   There are a number of sketches of answers, but no explicit solutions. A few answers wrongly conclude that the ratio of overtakes to being overtaken is equal to the ratio of slower to faster runners.

**Clevenson, Schilling, Watkins and Watkins (2001) "The Average Speed on the Highway"**

   They show that if the number of cars you pass is equal to the number of cars that pass you then you must be driving the average speed (not necessarily the median speed).

<!-- 
#           Notes

##           Post

Suppose you go for a run and you pass 90% of the people you see (the other 10% pass you). What's your overall rank in the distribution of speeds?

We can't know for sure, but if you assume the distribution of speeds is Normal then you're at approximately 80% (i.e. 80% of runners are slower and 20% are faster). The asymmetry is because you're relatively less likely to see people who run at a similar speed to you; you'll disproportionately encounter people who are far from you in the distribution of running speeds.


##      Matt:

> "I think I can get some bounds ... if r>1: since E|s-x| <= \sqrt E(s-x)^2 we get that s<=mean + (r-1)/(2 \sqrt{r}) sd. Only assumption is that mean and sd exist -- and I've done my sums right!"

Oh very nice, Matt. So if I pass 3x as many people as pass me, then I know that my speed cannot be more than about $0.58$ standard deviations above the mean ($=1/\sqrt{3}$). I do not think this argument gives a nontrivial lower bound beyond $s>\text{mean}$ when $r>1$.

##      Erik:

> "I think you’re less likely to see faster runners. The probability you intersect their path at the same time is lower because the time interval they’re there is shorter ... think (4) is related to length/size bias (https://en.wikipedia.org/wiki/Length_time_bias) I wasn't imagining the circular track scenario either, a straight line where people jump in at random points at random speeds. If you imagine runners are at every point in their run at once, and you draw a line at any point in the track at some instant, since a fast runner is on the track for less time you're less likely to hit their trajectory. I think depending on the setup of the problem this can vary -- i.e. depending on track shape, distribution of times spent running, and of speeds. Also I could be missing something"

Length-time bias:

>  "if the same number of slow-growing and fast-growing tumors appear in a year, the screening test detects more slow-growers than fast-growers. If the slow growing tumors are less likely to be fatal than the fast growers, the people whose cancer is detected by screening do better, on average, than the people whose tumors are detected from symptoms

[Data that speeds are lognormal](https://www.allendowney.com/blog/2023/10/28/why-are-you-so-slow/)



##           FB Post

My claim: keeping track of people you pass when you run will typically *exaggerate* your ranking in relative speed, e.g. if you pass people by with a ratio of 3:1 then you're probably not at the 75th percentile of speeds, you're significantly lower than that. (However this requires a sufficiently thin-tailed distribution of speeds).

More formally:

WITHOUT ASSUMPTION ON DISTRIBUTION

1. I cannot infer anything certain about my rank. Given the ratio of pass/passed-by, I could be in the 99th or 1st percentile. E.g. suppose the majority of runners were just slightly faster than me, but a few runners were much slower. Then I would pass many more runners than pass me, but nevertheless my rank among runners would be low.

2. I can infer whether I'm faster or slower than average. If the number of people who pass me is equal to the number of people by whom I'm passed then I must be going the *average* speed. If I pass more people than pass me then I must be going faster than average. As a corollary: if the distribution is symmetric (mean = median) then if you pass more people than pass you, you must have above-median speed.

WITH ASSUMPTION ON DISTRIBUTION

Let's say that "exaggeration" holds if your position in the passing distribution (passes/(passes+passedby)) is farther from 50% than your percentile in the distribution of speeds (slower/(faster+slower)).

1. If speeds are uniform then there's a very simple solution, and exaggeration will always hold. The ratio of slower/faster will be equal to the square root of the ratio of passes/passed-by. E.g. if I pass 100x as many people as pass me, then there will be only 10x as many people who are slower than me as there are people who are faster than me. There's a simple graphical derivation: the volume of people I pass (and am passed by) is given by the area of triangles on either side of my speed, and the areas of those triangles are proportional to the square of the number of runners.

2. If I assume a Normal distribution then there's an analytic solution. The solution is a little bit ugly, but exaggeration always holds: i.e. the share of people you pass always exceeds your percentile in the speed distribution.

However, with a $t$-distribution and low degrees of freedom, exaggeration won't always hold. I think there must be some condition on how fat-tailed the distribution is for exaggeration to hold. -->
