---
title: You Know When You're Wrong
author: Tom Cunningham
date: July 13 2024
draft: true
reference-location: document
---
<style>
/* dt { font-weight: bold; }
dd { margin-left: 4em; margin-bottom: 0.5em; } */
dl {display: grid;grid-template-columns: max-content auto;}
dt {grid-column-start: 1; width: 6cm;}
dd {grid-column-start: 2; margin-left: 2em;}
blockquote { font-style: italic; }
</style>

<!-- https://tecunningham.github.io/posts/2024-07-13-you-know-when-youre-wrong.html -->

Borel said you don't know when you're wrong.
: Borel said:
      
      > *"the inner certainty of someone who is making a mistake and answering wrongly is exactly the same as the inner certainty of someone who knows and is not making a mistake."*^[Andrew Parsloe copied this quote out for me and put it in a booklet he made for my 21st birthday. I found it again, re-reading the booklet recently.]

But you do know when you're wrong.

: Borel was mistaken: the two types of inner certainty are not the same, they are different. When you discover your mistake, when you see the truth, you recognize her, she is not a stranger.

Some recent mistakes I made:
:     - I under-estimated the share of users who performed a certain action over a 28-day period.
      - I dumped the milk straight into the flour, making the waffles lumpy.
      - I bought a pair of shoes that are ugly.
      <!-- - I thought the Uber would be quick. -->
      - I said something tart to someone I love.
      - I kicked the ball too hard.
      - I didn't mention an exception when making a generalization in a paper.
      - I drew a pair of eyes too almond-like, they didn't fit the nose.
      - I picked up my phone to check if I had new messages.
      - I bought an expensive croissant to take home to my family.
      - I thought "cuando" meant while.

When I made these mistakes I immediately recognized them as mistakes.
: I see the mistake and I get a shock of recognition. I open the cupboard to put away the can of coconut milk I bought and I see a dozen cans of coconut milk looking back at me. The mistake sometimes triggers a memory of making the same mistake my whole life, and it sometimes triggers a vision of making the same mistake through my remaining decades.

<!-- Some people say mistakes are residuals. Some people will tell you that a mistake by its consequences. because your decision led to a bad outcome doesn't mean it was a msitake. -->


People who have studied a little mathematics will often give lectures.
: They will say that you didn't make a mistake, that's *ex post* & this is *ex ante*. They will say attempted murder should be a crime, murder should not.
: That distinction picks out a certain type of mistake but I don't think it's the most common type of mistake. They are talking about mistakes from lack of information but we rarely lack information, we much more commonly lack clarity.

Imagine Borel in his study in Paris in 1941.
: He has been granted a vision into the crystalline structure of probability and he feels he can use this grace to set in order the many disordered ideas people have about judgment. But he overreaches. His satisfaction with the theory of probability gave him a hubris, an inner certainty that is qualitatively different from the inner certainty which people have who are right.

When Aristotle is reincarnated he will not say his problem was lack of information.
: Aristotle will visit the library and see that all the pieces of the jigsaw have been rearranged: the dolphin is now next to the cow, not the fish. The far East is next to the far West. The evening star is next to the morning star, and the sun fits in among one set of stars, and the moon a different set of stars. The races and sexes of humans are closer to each other than he had thought, and they also nestle close to the apes and the monkeys.
: He will see that we have collected more jigsaw pieces than he had but he will also observe that our arrangement of the pieces makes better sense of his own smaller collection, and he will kick himself for his mistake.

<!-- There are three types of mistake.
   : 1. Lack of information. These are Borel's mistakes: just residuals from too little information. In everyday life I think they are rare.
   : 2. Mistakes of confusion. You have enough information but it is not well organized in your brain. You know it implicitly.
   : 3. Mistakes of passion. Your instincts drag you towards some bad decision, that you know, in a certain sense, to be bad. -->

   <!-- _Strictly:_ suppose the ideal width is 2 inches, & then arriving towards the end I saw that the remaining dough was 5 inches wide. So I could have three slightly undersized (1.7) or two slightly oversized (2.5). Instead I chose neither: I kept cutting at 2 inches, so I'd be left with 3 inches, which I'd have to cut into 1.5. (the loss is convex in distance from the ideal size) -->
   <!-- Things this is like: (1) trying to satisfy two people you love and satisfying neither; (2) avoidance of awkwardness leading to even greater awkwardness in the future; (3)  -->


<!-- 
   -  Hypnotized intellectuals will repeat wrong things. They will say that only attempted murder should be illegal, not successful murder.
   - (And there is a very weak correlation between those who have the most information and those who make the fewest mistakes).
   - Post nut clarity.
   - I didn't floss my teeth
-->

#        Seminar Version

You have truth, signal, and decision.
: Let the truth be $v$, the signal $x$, and the decision $\hat{v}$.
: An *ex post* mistake is choosing the wrong thing:
   $$\hat{v}\neq v.$$
: An *ex ante* mistake is choosing the wrong thing given your information:
   $$\hat{v}\neq E[v|x].$$

My claim.
: I think the majority of decisions are ex ante mistakes: you could have made a better decision. If you reflected more deeply on your information then you would ==fix this==.




#        Appendix

A gratuitous mistake in cutting scones.
: I was cutting a roll of dough into squares to make scones, and as I let the knife fall I felt that I'd made a mistake but I wasn't sure what it was.
: It was a mistake of indecision: I had been hesitating on whether there was enough dough left for 3 strips or for 2: should I aim to cut a half or a third? Instead I cut down between them, a gratuitous indecisiveness, and I got one set of scones too-thin and another too-thick. Like a signwriter whose letters become progressively bunched up towards the end of the sign, a slow motion traffic accident.
: Many of my mistakes are like this: trying to satisfy two people I love and satisfying neither; avoidance of awkwardness leading to even greater awkwardness.

Borel (1950) [Probability and Certainty](https://archive.org/details/probabilitycerta0000bore/page/114/mode/2up?q=%22inner+certainty%22)
: > The problem of error has preoccupied philosophers since earliest antiquity. According to the subtle remark made by a famous Greek philosopher, the man who makes a mistake is twice ignorant, for he does not know the correct answer, and he does not know that he does not know it. This second ignorance is the really serious one, for the inner certainty of someone who is making a mistake and answering wrongly is exactly the same as the inner certainty of someone who knows and is not making a mistake. We all know that we are subject to error and that we sometimes make mistakes, entirely in good faith.


